import TwoDeck.Basic
import TwoDeck.Compose
import TwoDeck.Rotate
import TwoDeck.Grid
import TwoDeck.ShiftRows
import TwoDeck.SumRanks
import TwoDeck.PassKey
import TwoDeck.Factoradic
import TwoDeck.GridCycle
import TwoDeck.Round
import TwoDeck.Modes
