/-
  Generated by proofs/deprecated/doubledeal-v8/lean/witness_to_lean.py from
  ../witness_v8.json. Do not hand-edit; re-run the script (CI runs --check).
  VULNERABILITY PROOF data for deprecated DoubleDeal v8 only.
-/
namespace DoubleDealV8.Witness

/-- The two card ids swapped by tau. -/
def tauA : Nat := 12
def tauB : Nat := 51

/-- Random trials the search (attack/find_witness.py) needed. -/
def trials : Nat := 739

def key : List Nat := [18, 9, 29, 34, 51, 39, 5, 21, 38, 22, 30, 36, 43, 49, 33, 20, 41, 17, 24, 13, 0, 46, 42, 48, 45, 44, 16, 35, 25, 27, 6, 10, 28, 12, 19, 3, 26, 8, 47, 15, 31, 23, 7, 50, 40, 11, 32, 14, 37, 1, 2, 4]
def message : List Nat := [49, 40, 34, 14, 18, 16, 6, 45, 23, 37, 29, 3, 11, 9, 21, 30, 7, 20, 32, 46, 48, 47, 17, 36, 33, 41, 2, 42, 38, 26, 31, 51, 25, 10, 13, 35, 5, 24, 19, 22, 4, 8, 15, 39, 50, 43, 28, 0, 44, 12, 27, 1]
def cipher : List Nat := [42, 23, 9, 29, 19, 30, 6, 21, 41, 7, 18, 8, 27, 20, 34, 37, 13, 5, 48, 1, 51, 11, 49, 44, 24, 2, 38, 26, 43, 25, 46, 32, 36, 50, 15, 45, 12, 3, 22, 14, 16, 10, 0, 35, 39, 47, 31, 40, 28, 17, 33, 4]
/-- As recorded in the JSON: tau applied to `message`. -/
def messageTauJson : List Nat := [49, 40, 34, 14, 18, 16, 6, 45, 23, 37, 29, 3, 11, 9, 21, 30, 7, 20, 32, 46, 48, 47, 17, 36, 33, 41, 2, 42, 38, 26, 31, 12, 25, 10, 13, 35, 5, 24, 19, 22, 4, 8, 15, 39, 50, 43, 28, 0, 44, 51, 27, 1]
/-- As recorded in the JSON: E_K(tau M). -/
def cipherTauJson : List Nat := [42, 23, 9, 29, 19, 30, 6, 21, 41, 7, 18, 8, 27, 20, 34, 37, 13, 5, 48, 1, 12, 11, 49, 44, 24, 2, 38, 26, 43, 25, 46, 32, 36, 50, 15, 45, 51, 3, 22, 14, 16, 10, 0, 35, 39, 47, 31, 40, 28, 17, 33, 4]

end DoubleDealV8.Witness
