#!/usr/bin/env python3
"""Emit proofs/megadreifach/lean/MegaDreifach/Vectors.lean from the published KAT file
primitives/hash/megadreifach/kats/megaminx_hash_kats.json.

    python3 proofs/megadreifach/vectors/json_to_lean.py           # regenerate Vectors.lean
    python3 proofs/megadreifach/vectors/json_to_lean.py --check   # CI: fail if stale

Do not hand-copy KAT hexes into Lean. Besides the Vectors.lean comparison, --check (and
write mode) also fails if
- a vector is malformed (name not an identifier, hex not lower-case, msg_len != bytes of
  msg_hex, digest not digest_len bytes, padded_len / n_blocks inconsistent);
- proofs/megadreifach/vectors/megaminx_hash_kats.json is not a byte-identical copy of the
  published file;
- MegaDreifachHeavy/Kat.lean does not state, for every vector, (textually)
      theorem kat_<name> : Megadreifach.v_Hash (embed (hexBytes Vectors.vec_<name>.msgHex)) =
          .ok (embed (hexBytes Vectors.vec_<name>.digestHex))
  or states a kat_* theorem for a name that is not in the JSON (an early, readable lint).
It also writes / checks MegaDreifachHeavy/KatSpec.lean: one `#guard_expr` per vector
that pins the ELABORATED type of `kat_<name>` to the real constants (`_root_.` on every
name, syntactic `=ₛ`), so a local shadow of `Vectors.vec_*`, `hexBytes`, `embed` or
`v_Hash` fails the heavy build; and KatSpecCheck.lean, the same check as a program that
reads the constants' types without parsing any Kat-side syntax (run with
`lake env lean --run KatSpecCheck.lean` after the heavy build). Planted negatives:
vectors/katspec_negatives.py.
So each KAT input and digest is written once (the JSON), mirrored mechanically into
Vectors.lean, and the heavy theorems are about those very strings.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
DEFAULT_JSON = REPO / "primitives" / "hash" / "megadreifach" / "kats" / "megaminx_hash_kats.json"
COPY_JSON = HERE / "megaminx_hash_kats.json"
LEAN_DIR = HERE.parent / "lean"
DEFAULT_LEAN = LEAN_DIR / "MegaDreifach" / "Vectors.lean"
KAT_LEAN = LEAN_DIR / "MegaDreifachHeavy" / "Kat.lean"
SPEC_LEAN = LEAN_DIR / "MegaDreifachHeavy" / "KatSpec.lean"
CHECK_LEAN = LEAN_DIR / "KatSpecCheck.lean"
sys.path.insert(0, str(REPO / "tools"))
import gencheck  # noqa: E402

HEADER = """/-
  Generated by proofs/megadreifach/vectors/json_to_lean.py from
  primitives/hash/megadreifach/kats/megaminx_hash_kats.json. Do not hand-edit;
  re-run the script after the KAT file changes (CI runs it with --check).

  Every digest is kernel-checked against Generated.v_Hash on its own message in
  the heavy library: `MegaDreifachHeavy/Kat.lean` states, for each vector,
    kat_<name> : v_Hash (embed (hexBytes Vectors.vec_<name>.msgHex))
                   = .ok (embed (hexBytes Vectors.vec_<name>.digestHex))
  (`MegaDreifachHeavy/KatSpec.lean`, also generated, pins that elaborated type). The compiled metadata checks are in
  VectorCheck.lean (`lake exe megadreifach`). See proofs/ANTI_DRIFT.md.
-/
namespace MegaDreifach.Vectors

structure HashVec where
  name : String
  msgHex : String
  msgLen : Nat
  paddedLen : Nat
  nBlocks : Nat
  digestHex : String
deriving Repr, Inhabited

"""

FOOTER = """
end MegaDreifach.Vectors
"""

HEX = re.compile(r"^(?:[0-9a-f]{2})*$")
IDENT = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")


def problems(doc: dict) -> list[str]:
    bad = []
    dlen, block = int(doc["digest_len"]), int(doc["pad_block"])
    names = [v["name"] for v in doc["vectors"]]
    if len(set(names)) != len(names):
        bad.append("duplicate vector names")
    for v in doc["vectors"]:
        n = v["name"]
        if not IDENT.match(n):
            bad.append(f"{n!r}: name is not a Lean identifier")
        for key in ("msg_hex", "digest_hex"):
            if not HEX.match(v[key]):
                bad.append(f"{n}: {key} is not lower-case hex bytes")
        if len(v["msg_hex"]) // 2 != v["msg_len"]:
            bad.append(f"{n}: msg_len {v['msg_len']} != {len(v['msg_hex']) // 2} bytes of msg_hex")
        if len(v["digest_hex"]) != 2 * dlen:
            bad.append(f"{n}: digest_hex is not {dlen} bytes")
        # SHA-2 style pad to a multiple of the block: 0x80, zeros, 8-byte length.
        want = -(-(v["msg_len"] + 1 + 8) // block) * block
        if v["padded_len"] != want or v["n_blocks"] != want // block:
            bad.append(f"{n}: padded_len / n_blocks disagree with msg_len")
    for key in ("group_order_hex", "iv_cook12_digest_hex"):
        if not re.match(r"^(0x)?[0-9a-f]+$", doc[key]):
            bad.append(f"{key} is not lower-case hex")
    return bad


def kat_text_problems(doc: dict, raw: str) -> list[str]:
    """Readable early lint of Kat.lean (the binding check is the generated KatSpec.lean)."""
    text = re.sub(r"--[^\n]*", "", re.sub(r"/-.*?-/", "", raw, flags=re.S))
    declared = set(re.findall(r"^theorem\s+kat_(\w+)\s", text, flags=re.M))
    bad = []
    for v in doc["vectors"]:
        n = v["name"]
        stmt = (rf"^theorem\s+kat_{n}\s*:\s*Megadreifach\.v_Hash\s*\(embed\s*\(hexBytes\s+Vectors\.vec_{n}\.msgHex\)\)"
                rf"\s*=\s*\.ok\s*\(embed\s*\(hexBytes\s+Vectors\.vec_{n}\.digestHex\)\)\s*:=")
        if not re.search(stmt, text, flags=re.M):
            bad.append(f"Kat.lean does not state kat_{n} as v_Hash (embed (hexBytes Vectors.vec_{n}.msgHex)) "
                       f"= .ok (embed (hexBytes Vectors.vec_{n}.digestHex))")
    extra = declared - {v["name"] for v in doc["vectors"]}
    bad += [f"Kat.lean declares kat_{n} but the JSON has no vector {n!r}" for n in sorted(extra)]
    return bad


def kat_problems(doc: dict, kat_lean: Path) -> list[str]:
    if not kat_lean.exists():
        return [f"{kat_lean} is missing"]
    return kat_text_problems(doc, kat_lean.read_text())


def spec_guard(n: str) -> str:
    """The generated `#guard_expr` pinning the elaborated type of `kat_<n>`.

    Every constant is written with `_root_`, so no declaration, `open` or namespace in
    Kat.lean (or anything it imports) can redirect a name here; `=ₛ` compares the two
    elaborated `Expr`s syntactically (`==` after stripping metadata), so the KAT must be
    about exactly these constants."""
    vec = f"_root_.MegaDreifach.Vectors.vec_{n}"
    side = lambda field: (f"(_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes "
                          f"(_root_.MegaDreifach.Vectors.HashVec.{field} {vec})))")
    return (f"#guard_expr type_of% @_root_.MegaDreifach.Link2.Kat.kat_{n} =ₛ\n"
            f"  @_root_.Eq (_root_.Except _root_.SudoRt.Trap (_root_.Array _root_.Int))\n"
            f"    (_root_.Megadreifach.v_Hash {side('msgHex')})\n"
            f"    (@_root_.Except.ok _root_.SudoRt.Trap (_root_.Array _root_.Int) {side('digestHex')})\n")


SPEC_HEADER = """/-
  Generated by proofs/megadreifach/vectors/json_to_lean.py from
  primitives/hash/megadreifach/kats/megaminx_hash_kats.json. Do not hand-edit
  (CI runs the script with --check).

  Pins the statement of every KAT theorem in Kat.lean: for each vector, the
  elaborated type of `MegaDreifach.Link2.Kat.kat_<name>` must be, syntactically
  (`=ₛ`), `Megadreifach.v_Hash (embed (hexBytes vec_<name>.msgHex)) =
  .ok (embed (hexBytes vec_<name>.digestHex))` over the real constants (every name
  `_root_`-qualified). A local `def Vectors.vec_*`, `hexBytes`, `embed` or
  `Megadreifach.v_Hash` in Kat.lean (or an imported module) changes the constants
  in that type and fails the build of this module. Built with the heavy library
  (`lake build MegaDreifachHeavy`); planted negatives:
  proofs/megadreifach/vectors/katspec_negatives.py.
-/
import MegaDreifachHeavy.Kat
"""


def emit_spec(doc: dict) -> str:
    return SPEC_HEADER + "".join("\n" + spec_guard(v["name"]) for v in doc["vectors"])


CHECK_TEMPLATE = """/-
  Generated by proofs/megadreifach/vectors/json_to_lean.py from
  primitives/hash/megadreifach/kats/megaminx_hash_kats.json. Do not hand-edit
  (CI runs the script with --check).

  Second, syntax-independent copy of the KatSpec.lean check, run as a program after
  `lake build MegaDreifachHeavy`:
      lake env lean --run KatSpecCheck.lean
  It imports only `Lean`, loads MegaDreifachHeavy.Kat with `importModules` and
  compares the type of each `kat_<name>` constant with an `Expr` built here from
  constant names, so no syntax, macro or notation declared in Kat.lean (or in
  anything it imports) takes part: `#guard_expr` in KatSpec.lean is itself
  syntax that an imported `macro_rules` could rewrite, this is not. Each
  `kat_<name>` must be a theorem whose type is exactly (`==`)
    @Eq (Except SudoRt.Trap (Array Int))
      (Megadreifach.v_Hash (MegaDreifach.Link2.embed (MegaDreifach.hexBytes
        (MegaDreifach.Vectors.HashVec.msgHex MegaDreifach.Vectors.vec_<name>))))
      (@Except.ok SudoRt.Trap (Array Int) (MegaDreifach.Link2.embed
        (MegaDreifach.hexBytes (MegaDreifach.Vectors.HashVec.digestHex
          MegaDreifach.Vectors.vec_<name>))))
  Not in any lean_lib (it is a program, not a module of the package).
-/
import Lean
open Lean

def katNames : List String := [NAMES]

def katType (n : String) : Expr :=
  let vec := mkConst (Name.mkStr `MegaDreifach.Vectors ("vec_" ++ n))
  let side (field : String) : Expr :=
    mkApp (mkConst `MegaDreifach.Link2.embed)
      (mkApp (mkConst `MegaDreifach.hexBytes)
        (mkApp (mkConst (Name.mkStr `MegaDreifach.Vectors.HashVec field)) vec))
  let trap := mkConst `SudoRt.Trap
  let arr := mkApp (mkConst `Array [levelZero]) (mkConst `Int)
  mkApp3 (mkConst `Eq [levelOne]) (mkApp2 (mkConst `Except [levelZero, levelZero]) trap arr)
    (mkApp (mkConst `Megadreifach.v_Hash) (side "msgHex"))
    (mkApp3 (mkConst `Except.ok [levelZero, levelZero]) trap arr (side "digestHex"))

def main : IO UInt32 := do
  initSearchPath (← findSysroot)
  let env ← importModules #[{ module := `MegaDreifachHeavy.Kat }] {} 0
  let mut bad := 0
  for n in katNames do
    let c := Name.mkStr `MegaDreifach.Link2.Kat ("kat_" ++ n)
    match env.find? c with
    | some (.thmInfo v) =>
      if v.type.consumeMData == katType n then
        IO.println s!"KatSpecCheck: ok {c}"
      else
        IO.eprintln s!"KatSpecCheck: FAIL {c} has type {v.type}, expected {katType n}"
        bad := bad + 1
    | some _ => IO.eprintln s!"KatSpecCheck: FAIL {c} is not a theorem"; bad := bad + 1
    | none => IO.eprintln s!"KatSpecCheck: FAIL {c} is not declared"; bad := bad + 1
  IO.println s!"KatSpecCheck: {katNames.length - bad}/{katNames.length} KAT statements match"
  return if bad == 0 then 0 else 1
"""


def emit_check(doc: dict) -> str:
    return CHECK_TEMPLATE.replace("NAMES", ", ".join(f'"{v["name"]}"' for v in doc["vectors"]))


def emit(doc: dict) -> str:
    parts = [HEADER]
    parts.append(f"def digestLen : Nat := {int(doc['digest_len'])}\n")
    parts.append(f"def padBlock : Nat := {int(doc['pad_block'])}\n\n")
    parts.append("/-- `group_order_hex` of the KAT file. -/\n")
    parts.append(f"def groupOrderHex : String :=\n  \"{doc['group_order_hex']}\"\n\n")
    parts.append("/-- `iv_cook12_digest_hex` (IV-COOK12 digest) of the KAT file. -/\n")
    parts.append(f"def ivCook12DigestHex : String :=\n  \"{doc['iv_cook12_digest_hex']}\"\n")
    for v in doc["vectors"]:
        parts.append(f"\ndef vec_{v['name']} : HashVec where\n")
        parts.append(f"  name := \"{v['name']}\"\n")
        parts.append(f"  msgHex := \"{v['msg_hex']}\"\n")
        parts.append(f"  msgLen := {int(v['msg_len'])}\n")
        parts.append(f"  paddedLen := {int(v['padded_len'])}\n")
        parts.append(f"  nBlocks := {int(v['n_blocks'])}\n")
        parts.append(f"  digestHex := \"{v['digest_hex']}\"\n")
    names = ", ".join(f"vec_{v['name']}" for v in doc["vectors"])
    parts.append(f"\n/-- All {len(doc['vectors'])} vectors, in KAT-file order. -/\n")
    parts.append(f"def vectors : List HashVec :=\n  [{names}]\n")
    parts.append(FOOTER)
    return "".join(parts)


def main() -> int:
    p = gencheck.parser(__doc__)
    p.add_argument("--json", type=Path, default=DEFAULT_JSON)
    p.add_argument("--lean", type=Path, default=DEFAULT_LEAN)
    p.add_argument("--kat-lean", type=Path, default=KAT_LEAN)
    args = p.parse_args()
    doc = json.loads(args.json.read_text())
    bad = problems(doc) + kat_problems(doc, args.kat_lean)
    if args.json.resolve() == DEFAULT_JSON and COPY_JSON.read_bytes() != DEFAULT_JSON.read_bytes():
        bad.append(f"{COPY_JSON.relative_to(REPO)} is not a byte-identical copy of "
                   f"{DEFAULT_JSON.relative_to(REPO)}")
    for b in bad:
        print(f"json_to_lean: FAIL {b}", file=sys.stderr)
    fix = "python3 proofs/megadreifach/vectors/json_to_lean.py"
    rc = gencheck.emit(args.lean, emit(doc), args.check, fix=fix)
    rc |= gencheck.emit(SPEC_LEAN, emit_spec(doc), args.check, fix=fix)
    rc |= gencheck.emit(CHECK_LEAN, emit_check(doc), args.check, fix=fix)
    return 1 if bad else rc


if __name__ == "__main__":
    raise SystemExit(main())
