#!/usr/bin/env python3
"""Emit proofs/megadreifach/lean/MegaDreifach/Vectors.lean from the published KAT file
primitives/hash/megadreifach/kats/megaminx_hash_kats.json.

    python3 proofs/megadreifach/vectors/json_to_lean.py           # regenerate Vectors.lean
    python3 proofs/megadreifach/vectors/json_to_lean.py --check   # CI: fail if stale

Do not hand-copy KAT hexes into Lean. Besides the Vectors.lean comparison, --check (and
write mode) also fails if
- a vector is malformed (name not an identifier, hex not lower-case, msg_len != bytes of
  msg_hex, digest not digest_len bytes, padded_len / n_blocks inconsistent);
- proofs/megadreifach/vectors/megaminx_hash_kats.json is not a byte-identical copy of the
  published file;
- MegaDreifachHeavy/Kat.lean does not state, for every vector, exactly
      theorem kat_<name> : Megadreifach.v_Hash (embed (hexBytes Vectors.vec_<name>.msgHex)) =
          .ok (embed (hexBytes Vectors.vec_<name>.digestHex))
  (the qualified `Vectors.vec_<name>`; a bare `vec_<name>` is rejected), or states a
  kat_* theorem for a name that is not in the JSON;
- any Lean source of the package other than Vectors.lean (Kat.lean, MegaDreifach/,
  Generated/) declares a name containing `vec_` (def / abbrev / theorem / instance /
  opaque / axiom / notation / macro ...), which could shadow a generated vector.
So each KAT input and digest is written once (the JSON), mirrored mechanically into
Vectors.lean, and the heavy theorems are about those very strings.

    python3 proofs/megadreifach/vectors/json_to_lean.py --selftest  # planted negatives
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
DEFAULT_JSON = REPO / "primitives" / "hash" / "megadreifach" / "kats" / "megaminx_hash_kats.json"
COPY_JSON = HERE / "megaminx_hash_kats.json"
LEAN_DIR = HERE.parent / "lean"
DEFAULT_LEAN = LEAN_DIR / "MegaDreifach" / "Vectors.lean"
KAT_LEAN = LEAN_DIR / "MegaDreifachHeavy" / "Kat.lean"
sys.path.insert(0, str(REPO / "tools"))
import gencheck  # noqa: E402

HEADER = """/-
  Generated by proofs/megadreifach/vectors/json_to_lean.py from
  primitives/hash/megadreifach/kats/megaminx_hash_kats.json. Do not hand-edit;
  re-run the script after the KAT file changes (CI runs it with --check).

  Every digest is kernel-checked against Generated.v_Hash on its own message in
  the heavy library: `MegaDreifachHeavy/Kat.lean` states, for each vector,
    kat_<name> : v_Hash (embed (hexBytes Vectors.vec_<name>.msgHex))
                   = .ok (embed (hexBytes Vectors.vec_<name>.digestHex))
  (the script also checks that shape, and that no other source declares a `vec_*`). The compiled metadata checks are in
  VectorCheck.lean (`lake exe megadreifach`). See proofs/ANTI_DRIFT.md.
-/
namespace MegaDreifach.Vectors

structure HashVec where
  name : String
  msgHex : String
  msgLen : Nat
  paddedLen : Nat
  nBlocks : Nat
  digestHex : String
deriving Repr, Inhabited

"""

FOOTER = """
end MegaDreifach.Vectors
"""

HEX = re.compile(r"^(?:[0-9a-f]{2})*$")
IDENT = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")


def problems(doc: dict) -> list[str]:
    bad = []
    dlen, block = int(doc["digest_len"]), int(doc["pad_block"])
    names = [v["name"] for v in doc["vectors"]]
    if len(set(names)) != len(names):
        bad.append("duplicate vector names")
    for v in doc["vectors"]:
        n = v["name"]
        if not IDENT.match(n):
            bad.append(f"{n!r}: name is not a Lean identifier")
        for key in ("msg_hex", "digest_hex"):
            if not HEX.match(v[key]):
                bad.append(f"{n}: {key} is not lower-case hex bytes")
        if len(v["msg_hex"]) // 2 != v["msg_len"]:
            bad.append(f"{n}: msg_len {v['msg_len']} != {len(v['msg_hex']) // 2} bytes of msg_hex")
        if len(v["digest_hex"]) != 2 * dlen:
            bad.append(f"{n}: digest_hex is not {dlen} bytes")
        # SHA-2 style pad to a multiple of the block: 0x80, zeros, 8-byte length.
        want = -(-(v["msg_len"] + 1 + 8) // block) * block
        if v["padded_len"] != want or v["n_blocks"] != want // block:
            bad.append(f"{n}: padded_len / n_blocks disagree with msg_len")
    for key in ("group_order_hex", "iv_cook12_digest_hex"):
        if not re.match(r"^(0x)?[0-9a-f]+$", doc[key]):
            bad.append(f"{key} is not lower-case hex")
    return bad


# A declaration whose name contains `vec_` (in any namespace, e.g. `def vec_empty` or
# `def Vectors.vec_empty`), or a notation / macro mentioning it. Outside Vectors.lean
# such a name could shadow the generated vector the KAT statements refer to.
_MODS = r"(?:(?:private|protected|noncomputable|partial|unsafe|nonrec|local|scoped)\s+)*"
VEC_DECL = re.compile(
    r"^[ \t]*(?:@\[[^\]]*\]\s*)?(?:set_option\s+\S+\s+\S+\s+in\s+)*" + _MODS +
    r"(?:(?:def|abbrev|theorem|lemma|instance|opaque|axiom|structure|inductive|class)\s+[^\s:(\[{]*vec_"
    r"|(?:notation|macro|syntax|macro_rules|infix|infixl|infixr|prefix|postfix)\b[^\n]*vec_)",
    flags=re.M)


def strip_comments(text: str) -> str:
    return re.sub(r"--[^\n]*", "", re.sub(r"/-.*?-/", "", text, flags=re.S))


def vec_decl_problems(text: str, where: str) -> list[str]:
    return [f"{where} declares {m.group(0).strip()!r}: only Vectors.lean may declare vec_* names"
            for m in VEC_DECL.finditer(strip_comments(text))]


def kat_text_problems(doc: dict, raw: str) -> list[str]:
    text = strip_comments(raw)
    declared = set(re.findall(r"^theorem\s+kat_(\w+)\s", text, flags=re.M))
    bad = []
    for v in doc["vectors"]:
        n = v["name"]
        stmt = (rf"^theorem\s+kat_{n}\s*:\s*Megadreifach\.v_Hash\s*\(embed\s*\(hexBytes\s+Vectors\.vec_{n}\.msgHex\)\)"
                rf"\s*=\s*\.ok\s*\(embed\s*\(hexBytes\s+Vectors\.vec_{n}\.digestHex\)\)\s*:=")
        if not re.search(stmt, text, flags=re.M):
            bad.append(f"Kat.lean does not state kat_{n} as v_Hash (embed (hexBytes Vectors.vec_{n}.msgHex)) "
                       f"= .ok (embed (hexBytes Vectors.vec_{n}.digestHex))")
    extra = declared - {v["name"] for v in doc["vectors"]}
    bad += [f"Kat.lean declares kat_{n} but the JSON has no vector {n!r}" for n in sorted(extra)]
    return bad + vec_decl_problems(raw, "Kat.lean")


def kat_problems(doc: dict, kat_lean: Path, vectors_lean: Path = DEFAULT_LEAN) -> list[str]:
    if not kat_lean.exists():
        return [f"{kat_lean} is missing"]
    bad = kat_text_problems(doc, kat_lean.read_text())
    # The rest of the package (what Kat.lean imports, and Generated/) must not declare
    # vec_* names either (e.g. a `MegaDreifach.Link2.Vectors.vec_empty` would shadow
    # `Vectors.vec_empty` inside `namespace MegaDreifach.Link2.Kat`).
    for path in sorted(LEAN_DIR.rglob("*.lean")):
        if ".lake" in path.parts or path.resolve() in (kat_lean.resolve(), vectors_lean.resolve()):
            continue
        bad += vec_decl_problems(path.read_text(), str(path.relative_to(LEAN_DIR)))
    return bad


def selftest(doc: dict) -> int:
    """Planted negatives: each mutation of the committed Kat.lean must be rejected."""
    real = KAT_LEAN.read_text()
    n = doc["vectors"][0]["name"]
    q = f"Vectors.vec_{n}"
    anchor = "namespace MegaDreifach.Link2.Kat\n"
    shadow = f"def vec_{n} : Vectors.HashVec := {{ {q} with digestHex := \"00\" }}\n"
    cases = {
        "committed Kat.lean": (real, True),
        "bare vec_<name> in a KAT statement":
            (real.replace(f"(hexBytes {q}.msgHex)) =", f"(hexBytes vec_{n}.msgHex)) =", 1), False),
        "local def vec_<name>": (real.replace(anchor, anchor + shadow, 1), False),
        "local def Vectors.vec_<name>":
            (real.replace(anchor, anchor + shadow.replace(f"def vec_{n}", f"def {q}"), 1), False),
        "local abbrev vec_<name>": (real.replace(anchor, anchor + shadow.replace("def ", "abbrev "), 1), False),
        "private theorem vec_<name>_x":
            (real.replace(anchor, anchor + f"private theorem vec_{n}_x : True := trivial\n", 1), False),
        "instance vec_<name>":
            (real.replace(anchor, anchor + f"instance vec_{n} : Inhabited Nat := ⟨0⟩\n", 1), False),
        "local notation vec_<name>":
            (real.replace(anchor, anchor + f"local notation \"vec_{n}\" => {q}\n", 1), False),
    }
    failed = 0
    for what, (text, ok) in cases.items():
        assert ok or text != real, f"selftest mutation {what!r} did not apply"
        bad = kat_text_problems(doc, text)
        if (not bad) != ok:
            failed += 1
            print(f"json_to_lean selftest: FAIL {what}: expected {'accept' if ok else 'reject'}, "
                  f"got {bad or 'accept'}", file=sys.stderr)
        else:
            print(f"json_to_lean selftest: ok {what} ({'accepted' if ok else 'rejected: ' + bad[0]})")
    return 1 if failed else 0


def emit(doc: dict) -> str:
    parts = [HEADER]
    parts.append(f"def digestLen : Nat := {int(doc['digest_len'])}\n")
    parts.append(f"def padBlock : Nat := {int(doc['pad_block'])}\n\n")
    parts.append("/-- `group_order_hex` of the KAT file. -/\n")
    parts.append(f"def groupOrderHex : String :=\n  \"{doc['group_order_hex']}\"\n\n")
    parts.append("/-- `iv_cook12_digest_hex` (IV-COOK12 digest) of the KAT file. -/\n")
    parts.append(f"def ivCook12DigestHex : String :=\n  \"{doc['iv_cook12_digest_hex']}\"\n")
    for v in doc["vectors"]:
        parts.append(f"\ndef vec_{v['name']} : HashVec where\n")
        parts.append(f"  name := \"{v['name']}\"\n")
        parts.append(f"  msgHex := \"{v['msg_hex']}\"\n")
        parts.append(f"  msgLen := {int(v['msg_len'])}\n")
        parts.append(f"  paddedLen := {int(v['padded_len'])}\n")
        parts.append(f"  nBlocks := {int(v['n_blocks'])}\n")
        parts.append(f"  digestHex := \"{v['digest_hex']}\"\n")
    names = ", ".join(f"vec_{v['name']}" for v in doc["vectors"])
    parts.append(f"\n/-- All {len(doc['vectors'])} vectors, in KAT-file order. -/\n")
    parts.append(f"def vectors : List HashVec :=\n  [{names}]\n")
    parts.append(FOOTER)
    return "".join(parts)


def main() -> int:
    p = gencheck.parser(__doc__)
    p.add_argument("--json", type=Path, default=DEFAULT_JSON)
    p.add_argument("--lean", type=Path, default=DEFAULT_LEAN)
    p.add_argument("--kat-lean", type=Path, default=KAT_LEAN)
    p.add_argument("--selftest", action="store_true",
                   help="run the planted-negative tests of the Kat.lean checks and exit")
    args = p.parse_args()
    doc = json.loads(args.json.read_text())
    if args.selftest:
        return selftest(doc)
    bad = problems(doc) + kat_problems(doc, args.kat_lean)
    if args.json.resolve() == DEFAULT_JSON and COPY_JSON.read_bytes() != DEFAULT_JSON.read_bytes():
        bad.append(f"{COPY_JSON.relative_to(REPO)} is not a byte-identical copy of "
                   f"{DEFAULT_JSON.relative_to(REPO)}")
    for b in bad:
        print(f"json_to_lean: FAIL {b}", file=sys.stderr)
    rc = gencheck.emit(args.lean, emit(doc), args.check,
                       fix="python3 proofs/megadreifach/vectors/json_to_lean.py")
    return 1 if bad else rc


if __name__ == "__main__":
    raise SystemExit(main())
