/-
  Generated by proofs/megadreifach/vectors/json_to_lean.py from
  primitives/hash/megadreifach/kats/megaminx_hash_kats.json. Do not hand-edit
  (CI runs the script with --check).

  Second, syntax-independent copy of the KatSpec.lean check, run as a program after
  `lake build MegaDreifachHeavy`:
      lake env lean --run KatSpecCheck.lean
  It imports only `Lean`, loads MegaDreifachHeavy.Kat with `importModules` and
  compares the type of each `kat_<name>` constant with an `Expr` built here from
  constant names, so no syntax, macro or notation declared in Kat.lean (or in
  anything it imports) takes part: `#guard_expr` in KatSpec.lean is itself
  syntax that an imported `macro_rules` could rewrite, this is not. Each
  `kat_<name>` must be a theorem whose type is exactly (`==`)
    @Eq (Except SudoRt.Trap (Array Int))
      (Megadreifach.v_Hash (MegaDreifach.Link2.embed (MegaDreifach.hexBytes
        (MegaDreifach.Vectors.HashVec.msgHex MegaDreifach.Vectors.vec_<name>))))
      (@Except.ok SudoRt.Trap (Array Int) (MegaDreifach.Link2.embed
        (MegaDreifach.hexBytes (MegaDreifach.Vectors.HashVec.digestHex
          MegaDreifach.Vectors.vec_<name>))))
  Not in any lean_lib (it is a program, not a module of the package).
-/
import Lean
open Lean

def katNames : List String := ["empty", "short_abc", "short_one", "edge_27", "edge_28", "edge_29", "multi_56", "multi_100"]

def katType (n : String) : Expr :=
  let vec := mkConst (Name.mkStr `MegaDreifach.Vectors ("vec_" ++ n))
  let side (field : String) : Expr :=
    mkApp (mkConst `MegaDreifach.Link2.embed)
      (mkApp (mkConst `MegaDreifach.hexBytes)
        (mkApp (mkConst (Name.mkStr `MegaDreifach.Vectors.HashVec field)) vec))
  let trap := mkConst `SudoRt.Trap
  let arr := mkApp (mkConst `Array [levelZero]) (mkConst `Int)
  mkApp3 (mkConst `Eq [levelOne]) (mkApp2 (mkConst `Except [levelZero, levelZero]) trap arr)
    (mkApp (mkConst `Megadreifach.v_Hash) (side "msgHex"))
    (mkApp3 (mkConst `Except.ok [levelZero, levelZero]) trap arr (side "digestHex"))

def main : IO UInt32 := do
  initSearchPath (← findSysroot)
  let env ← importModules #[{ module := `MegaDreifachHeavy.Kat }] {} 0
  let mut bad := 0
  for n in katNames do
    let c := Name.mkStr `MegaDreifach.Link2.Kat ("kat_" ++ n)
    match env.find? c with
    | some (.thmInfo v) =>
      if v.type.consumeMData == katType n then
        IO.println s!"KatSpecCheck: ok {c}"
      else
        IO.eprintln s!"KatSpecCheck: FAIL {c} has type {v.type}, expected {katType n}"
        bad := bad + 1
    | some _ => IO.eprintln s!"KatSpecCheck: FAIL {c} is not a theorem"; bad := bad + 1
    | none => IO.eprintln s!"KatSpecCheck: FAIL {c} is not declared"; bad := bad + 1
  IO.println s!"KatSpecCheck: {katNames.length - bad}/{katNames.length} KAT statements match"
  return if bad == 0 then 0 else 1
