import MegaDreifach

def main : IO UInt32 := do
  IO.println "MegaDreifach v2 (C36) Lean formalization (correctness; Generated from megadreifach.sudo v2)"
  IO.println "Proved: position model + legality (M1),"
  IO.println "        compose assoc / inverse round-trip (M2),"
  IO.println "        digest encoding injective on reachable positions (M3; no unrank),"
  IO.println "        factoradic φ injectivity for n < 2^224 and the φ(φ⁻¹) round trip (M4),"
  IO.println "        pad B=28 injectivity and length recovery (M5),"
  IO.println "        DM algebra / 3-solve invariant (M6),"
  IO.println "        HashDeckBody require_permutation (M7),"
  IO.println "        G2 one-card injectivity with the 60×52 v2 nets kernel-checked (M8),"
  IO.println "        M9 for 2-card windows (InjPos W, GripOk grip, cards < 52, same deal positions;"
  IO.println "        rotation covariance + kernel-checked decoder certificate; not block-level)."
  IO.println "Link 2: Generated.v_Hash = algebraic MD fold on PadWf (v_Hash_refines);"
  IO.println "        Generated.v_HashDeck = v_Hash of the Lehmer rank on PhiInvWf (v_HashDeck_refines);"
  IO.println "        8 v2 KATs as v_Hash theorems in lean_lib MegaDreifachHeavy (M13)."
  IO.println "Security layer (v2; reductions, not a security claim): MD reduction; step-word / parity lemmas."
  IO.println "The v1 weakness proofs (SwapCollision, CornerDriven, FreeStart) are in the frozen"
  IO.println "        package proofs/deprecated/megadreifach-v1 (namespace MegaDreifachV1)."
  IO.println "Open: digest unrank (surjectivity);"
  IO.println "        sudo = Generated (Link 1)."
  IO.println "These are correctness / algebraic theorems; sudo = Generated is trusted,"
  IO.println "and nothing here is a bit-security claim (see ANTI_DRIFT.md)."
  MegaDreifach.runVectorChecks
