/-
  Heavy MegaDreifach theorems: the eight hash KATs as kernel-checked
  (`decide!`) theorems about Generated `v_Hash` (M13), about 8 min of kernel
  evaluation. NOT in the default build target; see the `megadreifach-heavy`
  CI job (proofs-heavy.yml). Build with `lake build MegaDreifachHeavy`.
-/
import MegaDreifachHeavy.Kat
-- generated by vectors/json_to_lean.py: pins the elaborated type of every kat_<name>
import MegaDreifachHeavy.KatSpec
