#!/usr/bin/env python3
"""Rewrite the five expected ciphertexts in DoubleDealSecurityHeavy/RealKey.lean
(between the BEGIN/END GENERATED markers) from the v12 Python port, via
v10sym_subgroup.witnesses(). --check: compare only (seconds; no Lean).
usage: python3 realkey_to_lean.py [--check]"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import v10sym_subgroup as W
from ddport import REPO
sys.path.insert(0, str(REPO / 'tools'))
from gencheck import parser, emit
args = parser(__doc__).parse_args()
path = REPO / 'proofs/doubledeal/security/DoubleDealSecurityHeavy/RealKey.lean'
BEGIN = '-- BEGIN GENERATED by checks/realkeys/realkey_to_lean.py (do not hand-edit; CI runs --check)\n'
END = '-- END GENERATED\n'
L = lambda xs: '[' + ', '.join(map(str, xs)) + ']'
blocks = []
for name, doc, msg, out in W.witnesses():
    blocks.append(f'''/-- (PROVED, kernel `decide!`) {doc}, identity master key. -/
theorem {name} :
    encryptDeck (toDeck {msg}) (List.range 52) = {L(out)} := by
  decide!
''')
have = path.read_text()
i, j = have.index(BEGIN) + len(BEGIN), have.index(END)
sys.exit(emit(path, have[:i] + '\n'.join(blocks) + have[j:], args.check,
              fix='python3 proofs/doubledeal/security/checks/realkeys/realkey_to_lean.py'))
