#!/usr/bin/env python3
"""Emit proofs/megadreifach-v3/lean/MegaDreifachV3/Vectors.lean from the v3 KAT file
primitives/hash/megadreifach/kats/megaminx_hash_kats_v3.json.

    python3 proofs/megadreifach-v3/vectors/json_to_lean.py           # regenerate Vectors.lean
    python3 proofs/megadreifach-v3/vectors/json_to_lean.py --check   # CI: fail if stale

Do not hand-copy KAT hexes into Lean. The JSON itself is produced by
primitives/hash/megadreifach/kats/regen_v3.mjs from the sudoc JS build of the v3 sudo;
this script only mirrors it into Lean data. Besides the Vectors.lean comparison, --check
(and write mode) fails if a vector is malformed: name not an identifier, hex not
lower-case, msg_len != bytes of msg_hex, a digest that is not digest_len bytes,
padded_len / n_blocks inconsistent with pad_block, or a deal that is not a permutation of
0..51.

The data is checked against the compiled emitted code by MegaDreifachV3/KatRun.lean
(`lake exe megadreifach_v3_kat`). That is compiled evaluation, not a kernel proof.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
JSON = REPO / "primitives" / "hash" / "megadreifach" / "kats" / "megaminx_hash_kats_v3.json"
OUT = HERE.parent / "lean" / "MegaDreifachV3" / "Vectors.lean"
sys.path.insert(0, str(REPO / "tools"))
import gencheck  # noqa: E402

HEX = re.compile(r"^(?:[0-9a-f]{2})*$")
NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def fail(msg: str) -> None:
    raise SystemExit(f"json_to_lean (v3): {msg}")


def check_hex(what: str, h: str, nbytes: int | None = None) -> None:
    if not HEX.match(h):
        fail(f"{what}: not lower-case hex of whole bytes: {h!r}")
    if nbytes is not None and len(h) != 2 * nbytes:
        fail(f"{what}: {len(h) // 2} bytes, expected {nbytes}")


def check_deal(what: str, deal: list) -> None:
    if sorted(deal) != list(range(52)):
        fail(f"{what}: deal_ids is not a permutation of 0..51")


def lean_str(s: str) -> str:
    return '"' + s + '"'


def lean_nats(xs: list) -> str:
    return "#[" + ", ".join(str(int(x)) for x in xs) + "]"


def render(d: dict) -> str:
    if d.get("version") != "v3":
        fail(f"version is {d.get('version')!r}, expected 'v3'")
    dl, pb = d["digest_len"], d["pad_block"]
    check_hex("iv_cook12_digest_hex", d["iv_cook12_digest_hex"], dl)
    out = [
        "/-",
        "  Generated by proofs/megadreifach-v3/vectors/json_to_lean.py from",
        "  primitives/hash/megadreifach/kats/megaminx_hash_kats_v3.json. Do not hand-edit;",
        "  re-run the script after the KAT file changes (CI runs it with --check).",
        "",
        "  Data only. MegaDreifachV3/KatRun.lean (`lake exe megadreifach_v3_kat`) runs the",
        "  compiled emitted v3 code on it. That is compiled evaluation, not a kernel proof.",
        "  See proofs/ANTI_DRIFT.md.",
        "-/",
        "namespace MegaDreifachV3.Vectors",
        "",
        "structure HashVec where",
        "  name : String",
        "  msgHex : String",
        "  msgLen : Nat",
        "  paddedLen : Nat",
        "  nBlocks : Nat",
        "  digestHex : String",
        "deriving Repr, Inhabited",
        "",
        "structure DealVec where",
        "  name : String",
        "  deal : Array Nat",
        "  digestHex : String",
        "deriving Repr, Inhabited",
        "",
        f"def digestLen : Nat := {dl}",
        f"def padBlock : Nat := {pb}",
        "",
        "/-- `iv_cook12_digest_hex` (IV-COOK12 digest) of the KAT file. -/",
        "def ivCook12DigestHex : String :=",
        f"  {lean_str(d['iv_cook12_digest_hex'])}",
        "",
    ]
    names = []
    for v in d["vectors"]:
        n = v["name"]
        if not NAME.match(n):
            fail(f"vector name {n!r} is not an identifier")
        check_hex(f"{n}.msg_hex", v["msg_hex"])
        check_hex(f"{n}.digest_hex", v["digest_hex"], dl)
        if len(v["msg_hex"]) != 2 * v["msg_len"]:
            fail(f"{n}: msg_len {v['msg_len']} != bytes of msg_hex")
        if v["padded_len"] % pb or v["padded_len"] // pb != v["n_blocks"]:
            fail(f"{n}: padded_len / n_blocks inconsistent with pad_block {pb}")
        names.append(n)
        out += [
            f"def vec_{n} : HashVec where",
            f"  name := {lean_str(n)}",
            f"  msgHex := {lean_str(v['msg_hex'])}",
            f"  msgLen := {v['msg_len']}",
            f"  paddedLen := {v['padded_len']}",
            f"  nBlocks := {v['n_blocks']}",
            f"  digestHex := {lean_str(v['digest_hex'])}",
            "",
        ]
    out += ["def vectors : List HashVec :=", "  [" + ", ".join(f"vec_{n}" for n in names) + "]", ""]
    hd = d["hash_deck"]
    check_deal("hash_deck", hd["deal_ids"])
    check_hex("hash_deck.digest_hex", hd["digest_hex"], dl)
    out += [
        "/-- `hash_deck` of the KAT file: HashDeck of this deal (the file's note: deal = phi(0^28),",
        f"    and `match_hash_bytes_zero28` = {str(hd.get('match_hash_bytes_zero28')).lower()}). -/",
        "def hashDeck : DealVec where",
        '  name := "hash_deck"',
        f"  deal := {lean_nats(hd['deal_ids'])}",
        f"  digestHex := {lean_str(hd['digest_hex'])}",
        "",
        "/-- `hash_deck.match_hash_bytes_zero28` of the KAT file. -/",
        f"def hashDeckMatchesZero28 : Bool := {str(bool(hd.get('match_hash_bytes_zero28'))).lower()}",
        "",
    ]
    bnames = []
    for i, b in enumerate(d["body_vectors"]):
        check_deal(f"body_vectors[{i}]", b["deal_ids"])
        check_hex(f"body_vectors[{i}].digest_hex", b["digest_hex"], dl)
        bnames.append(f"body_{i}")
        out += [
            f"/-- `body_vectors[{i}]` of the KAT file: HashDeckBody of this deal. -/",
            f"def body_{i} : DealVec where",
            f'  name := "body_vectors[{i}]"',
            f"  deal := {lean_nats(b['deal_ids'])}",
            f"  digestHex := {lean_str(b['digest_hex'])}",
            "",
        ]
    out += ["def bodyVectors : List DealVec :=", "  [" + ", ".join(bnames) + "]", "",
            "end MegaDreifachV3.Vectors", ""]
    return "\n".join(out)


def main() -> int:
    args = gencheck.parser(__doc__).parse_args()
    return gencheck.emit(OUT, render(json.loads(JSON.read_text())), args.check)


if __name__ == "__main__":
    sys.exit(main())
