/-
  Generated by proofs/megadreifach/vectors/json_to_lean.py from
  primitives/hash/megadreifach/kats/megaminx_hash_kats_v2.json. Do not hand-edit;
  re-run the script after the KAT file changes (CI runs it with --check).

  Every digest is kernel-checked against Generated.v_Hash on its own message in
  the heavy library: `MegaDreifachHeavy/Kat.lean` states, for each vector,
    kat_<name> : v_Hash (embed (hexBytes Vectors.vec_<name>.msgHex))
                   = .ok (embed (hexBytes Vectors.vec_<name>.digestHex))
  (`KatSpecCheck.lean`, also generated, pins that elaborated type). The compiled metadata checks are in
  VectorCheck.lean (`lake exe megadreifach`). See proofs/ANTI_DRIFT.md.
-/
namespace MegaDreifach.Vectors

structure HashVec where
  name : String
  msgHex : String
  msgLen : Nat
  paddedLen : Nat
  nBlocks : Nat
  digestHex : String
deriving Repr, Inhabited

def digestLen : Nat := 29
def padBlock : Nat := 28

/-- `group_order_hex` of the KAT file. -/
def groupOrderHex : String :=
  "0x3bbea482ed28698b1ec5fb346d240d1433047d5800000000000000000"

/-- `iv_cook12_digest_hex` (IV-COOK12 digest) of the KAT file. -/
def ivCook12DigestHex : String :=
  "0000021aeb876eb76dd8bf833457a2c02613e55656963e02d8dfedb5aa"

def vec_empty : HashVec where
  name := "empty"
  msgHex := ""
  msgLen := 0
  paddedLen := 28
  nBlocks := 1
  digestHex := "00177fb4f00c600607ae0bae37ecead977302d40d46037b67f0860155f"

def vec_short_abc : HashVec where
  name := "short_abc"
  msgHex := "616263"
  msgLen := 3
  paddedLen := 28
  nBlocks := 1
  digestHex := "02127ee2a640fdd7f250205c877e0c19c8a7899e2fc9b534cd1d4c7052"

def vec_short_one : HashVec where
  name := "short_one"
  msgHex := "00"
  msgLen := 1
  paddedLen := 28
  nBlocks := 1
  digestHex := "02a726760fd2255096ed3e9c69239a3df004555905cd90182081ea2c1a"

def vec_edge_27 : HashVec where
  name := "edge_27"
  msgHex := "000102030405060708090a0b0c0d0e0f101112131415161718191a"
  msgLen := 27
  paddedLen := 56
  nBlocks := 2
  digestHex := "027fbcf196cd38b393d89784f448a2d818c415dbb4537a09f4c819b921"

def vec_edge_28 : HashVec where
  name := "edge_28"
  msgHex := "000102030405060708090a0b0c0d0e0f101112131415161718191a1b"
  msgLen := 28
  paddedLen := 56
  nBlocks := 2
  digestHex := "01f5de7e2f8e994ad60043363fe238d88e261f4f47cde01f446008adcf"

def vec_edge_29 : HashVec where
  name := "edge_29"
  msgHex := "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c"
  msgLen := 29
  paddedLen := 56
  nBlocks := 2
  digestHex := "00efebf3a9880f40fdd9a728c13b6c08532b5d2ebba2944f2adae96c4d"

def vec_multi_56 : HashVec where
  name := "multi_56"
  msgHex := "6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d"
  msgLen := 56
  paddedLen := 84
  nBlocks := 3
  digestHex := "019346954a7da2744a5d52b0d8d3c33cdcb92832da140f8d8d68b18a21"

def vec_multi_100 : HashVec where
  name := "multi_100"
  msgHex := "00112233445566778899aabbccddeeff102132435465768798a9bacbdcedfe0f2031425364758697a8b9cadbecfd0e1f30415263748596a7b8c9daebfc0d1e2f405162738495a6b7c8d9eafb0c1d2e3f5061728394a5b6c7d8e9fa0b1c2d3e4f60718293"
  msgLen := 100
  paddedLen := 112
  nBlocks := 4
  digestHex := "0279a3d0ae68fe0a23ba9cf9021be4a957ff001f2994b203c4395fbde6"

/-- All 8 vectors, in KAT-file order. -/
def vectors : List HashVec :=
  [vec_empty, vec_short_abc, vec_short_one, vec_edge_27, vec_edge_28, vec_edge_29, vec_multi_56, vec_multi_100]

end MegaDreifach.Vectors
