/-
  Generated by proofs/megadreifach/vectors/json_to_lean.py from
  primitives/hash/megadreifach/kats/megaminx_hash_kats.json. Do not hand-edit;
  re-run the script after the KAT file changes (CI runs it with --check).

  Every digest is kernel-checked against Generated.v_Hash on its own message in
  the heavy library: `MegaDreifachHeavy/Kat.lean` states, for each vector,
    kat_<name> : v_Hash (embed (hexBytes Vectors.vec_<name>.msgHex))
                   = .ok (embed (hexBytes Vectors.vec_<name>.digestHex))
  (`MegaDreifachHeavy/KatSpec.lean`, also generated, pins that elaborated type). The compiled metadata checks are in
  VectorCheck.lean (`lake exe megadreifach`). See proofs/ANTI_DRIFT.md.
-/
namespace MegaDreifach.Vectors

structure HashVec where
  name : String
  msgHex : String
  msgLen : Nat
  paddedLen : Nat
  nBlocks : Nat
  digestHex : String
deriving Repr, Inhabited

def digestLen : Nat := 29
def padBlock : Nat := 28

/-- `group_order_hex` of the KAT file. -/
def groupOrderHex : String :=
  "0x3bbea482ed28698b1ec5fb346d240d1433047d5800000000000000000"

/-- `iv_cook12_digest_hex` (IV-COOK12 digest) of the KAT file. -/
def ivCook12DigestHex : String :=
  "0000021aeb876eb76dd8bf833457a2c02613e55656963e02d8dfedb5aa"

def vec_empty : HashVec where
  name := "empty"
  msgHex := ""
  msgLen := 0
  paddedLen := 28
  nBlocks := 1
  digestHex := "037ef5274eebea6ed847821573d575f9d7a0d593d31787d8a50bedf55e"

def vec_short_abc : HashVec where
  name := "short_abc"
  msgHex := "616263"
  msgLen := 3
  paddedLen := 28
  nBlocks := 1
  digestHex := "025959c0ab2cdad7536956e3490cec6b2711b5d73c5731af2d4ecff550"

def vec_short_one : HashVec where
  name := "short_one"
  msgHex := "00"
  msgLen := 1
  paddedLen := 28
  nBlocks := 1
  digestHex := "02e8785e47149ea0d03cc39c4ffd5c3ee21568197394a48744cc3c53f5"

def vec_edge_27 : HashVec where
  name := "edge_27"
  msgHex := "000102030405060708090a0b0c0d0e0f101112131415161718191a"
  msgLen := 27
  paddedLen := 56
  nBlocks := 2
  digestHex := "01d701043ab21d88a52ffed94b46896dc18e15f775c3d661fec3f9fed8"

def vec_edge_28 : HashVec where
  name := "edge_28"
  msgHex := "000102030405060708090a0b0c0d0e0f101112131415161718191a1b"
  msgLen := 28
  paddedLen := 56
  nBlocks := 2
  digestHex := "0354488e90201f310b87eb4cdda3ac1fabcd9671fd08f4836b325cf8f1"

def vec_edge_29 : HashVec where
  name := "edge_29"
  msgHex := "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c"
  msgLen := 29
  paddedLen := 56
  nBlocks := 2
  digestHex := "01b991a6db6297877c7c4f72283cf3f6c8e7a3f91f0a82c141562b9835"

def vec_multi_56 : HashVec where
  name := "multi_56"
  msgHex := "6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d"
  msgLen := 56
  paddedLen := 84
  nBlocks := 3
  digestHex := "00a5059319ad22533bc2156fa140dc17d8969dfa6bafe751848eebe724"

def vec_multi_100 : HashVec where
  name := "multi_100"
  msgHex := "00112233445566778899aabbccddeeff102132435465768798a9bacbdcedfe0f2031425364758697a8b9cadbecfd0e1f30415263748596a7b8c9daebfc0d1e2f405162738495a6b7c8d9eafb0c1d2e3f5061728394a5b6c7d8e9fa0b1c2d3e4f60718293"
  msgLen := 100
  paddedLen := 112
  nBlocks := 4
  digestHex := "0156e9f32a565e585893eab5229ea6a12c959c743d9c3e420827139e20"

/-- All 8 vectors, in KAT-file order. -/
def vectors : List HashVec :=
  [vec_empty, vec_short_abc, vec_short_one, vec_edge_27, vec_edge_28, vec_edge_29, vec_multi_56, vec_multi_100]

end MegaDreifach.Vectors
