// Regenerate kats/megaminx_hash_kats_v3.json from the runnable spec: the sudoc JS build of
// v3/megadreifach.sudo. Nothing here computes a digest itself.
//
// Usage, from the repo root:
//   sudoc build --target js -o /tmp/megadreifach-v3 primitives/hash/megadreifach/v3/megadreifach.sudo
//   MD3_OUT=/tmp/megadreifach-v3 node primitives/hash/megadreifach/kats/regen_v3.mjs [--check]
// --check (same convention as tools/gencheck.py): never write; print "OK <file>" if a fresh run
// reproduces the committed JSON byte for byte, else "STALE <file>" and exit 1.
// tools/generate-demos.sh runs it with --check. The independent check is
// proofs/megadreifach/security/v3/check_v3.py (a Python transliteration of SPEC v3 §5).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const args = process.argv.slice(2);
const check = args.includes("--check");
const unknown = args.filter((a) => a !== "--check");
if (unknown.length) {
    console.error(`regen_v3.mjs: unknown argument(s) ${unknown.join(" ")} (usage: regen_v3.mjs [--check])`);
    process.exit(2);
}
const here = dirname(fileURLToPath(import.meta.url));
const out = process.env.MD3_OUT || "/tmp/megadreifach-v3";
const md = await import(join(out, "megadreifach.mjs"));
const path = join(here, "megaminx_hash_kats_v3.json");
const repo = join(here, "..", "..", "..", "..");

const hex = (b) => b.map((x) => x.toString(16).padStart(2, "0")).join("");
const range = (n) => [...Array(n).keys()];

// Same message inputs and order as the v1 and v2 files.
const msgs = [
    ["empty", []],
    ["short_abc", [97, 98, 99]],
    ["short_one", [0]],
    ["edge_27", range(27)],
    ["edge_28", range(28)],
    ["edge_29", range(29)],
    ["multi_56", Array(56).fill(109)],
    ["multi_100", range(100).map((i) => (i * 17) % 256)],
];
const vectors = msgs.map(([name, m]) => {
    const padded = md.pad_message(m).length;
    return { name, msg_hex: hex(m), msg_len: m.length, padded_len: padded, n_blocks: padded / 28, digest_hex: hex(md.Hash(m)) };
});

// HashDeckBody vectors on fixed pseudo-random deals (Fisher-Yates driven by a 31-bit LCG,
// seed 20261002 + i). Deals 4..7 have a King moved to position 52 so the held card of the
// echoes is a King (it turns the face opposite the echo colour and names on the Ace colour).
function deal(i) {
    let x = 20261002 + i;
    const d = range(52);
    for (let j = 51; j > 0; j--) {
        x = (x * 1103515245 + 12345) % 2147483648;
        const r = x % (j + 1);
        [d[j], d[r]] = [d[r], d[j]];
    }
    if (i >= 4) {
        const king = 48 + (i - 4);
        const at = d.indexOf(king);
        [d[at], d[51]] = [d[51], d[at]];
    }
    return d;
}
const body_vectors = range(8).map((i) => {
    const d = deal(i);
    return { deal_ids: d, digest_hex: hex(md.HashDeckBody(d)) };
});

const ident = range(52);
const kats = {
    spec: "MegaDreifach",
    version: "v3",
    status: "Candidate (v2 stays current until a separate change makes v3 current). Not a security claim. MegaDreifach v3 = card phase ZP26: colour-named card steps with a last-face register, deal once, 26 echoes of the held 52nd card (SPEC v3 section 5); no grips, no F3 rounds.",
    date: "2026-10-02",
    digest_encoding: "LOCKED position_to_bytes 29-byte BE rank (SPEC v2 sections 3 and 6, unchanged)",
    digest_len: 29,
    pad_block: 28,
    body: 52,
    echoes: 26,
    iv: "IV-COOK12",
    dm: "compose(h, E_m(h)) = h * W * h, soft-lock 3-puzzle (unchanged)",
    iv_cook12_digest_hex: "0000021aeb876eb76dd8bf833457a2c02613e55656963e02d8dfedb5aa",
    vectors,
    hash_deck: {
        note: "deal = phi(0^28); hash_deck = hash_bytes(0^28)",
        deal_ids: ident,
        digest_hex: hex(md.HashDeck(ident)),
        match_hash_bytes_zero28: hex(md.HashDeck(ident)) === hex(md.Hash(Array(28).fill(0))),
    },
    body_vectors,
    digest_note: "Generated by kats/regen_v3.mjs from the sudoc JS build of v3/megadreifach.sudo (the runnable spec). Checked equal to an independent Python transliteration of SPEC v3 section 5 (proofs/megadreifach/security/v3/check_v3.py) and to the fast engine the v3 statistics were computed with. The sudo tests assert the eight Hash digests and the HashDeck vector.",
};
const text = JSON.stringify(kats, null, 2) + "\n";
const rel = relative(repo, path);
if (check) {
    let old = "";
    try { old = readFileSync(path, "utf8"); } catch { /* missing */ }
    if (old === text) {
        console.log(`OK ${rel}`);
    } else {
        console.log(`STALE ${rel}`);
        console.error(`regenerate: MD3_OUT=${out} node ${relative(repo, fileURLToPath(import.meta.url))}`);
        process.exit(1);
    }
} else {
    writeFileSync(path, text);
    console.log(`wrote ${rel}`);
}
