/-
  PROOF-ONLY (SPEC §6 S3 / S4). Sudo does not emit these theorems.

  The algorithm is Generated.passkey / Generated.passkey_inv (from
  doubledeal.sudo). This file is a Fin/List model so the inverse lemmas
  typecheck. Link 2 glues `Generated.passkey` ≃ `passToKeyCutFallback`
  and `Generated.passkey_inv` ≃ `passToKeyCutFallbackInv` on every
  well-formed list. NEXT is encrypt refinement. Do not edit this file
  to "fix encrypt".
-/
import DoubleDeal.Basic
import DoubleDeal.Rotate

namespace DoubleDeal

/- Lean 4.14 core has no `Function.LeftInverse` (it lives in Mathlib). These
   local versions stay in the `DoubleDeal` namespace so the package can be
   imported next to Mathlib (proofs/doubledeal/security). -/
def LeftInverse (g : β → α) (f : α → β) : Prop := ∀ x, g (f x) = x
def RightInverse (g : β → α) (f : α → β) : Prop := LeftInverse f g

def cutProper (xs : List α) (r : Nat) : List α :=
  if r < xs.length then rotL xs r else xs

theorem cutProper_perm (xs : List α) (r : Nat) :
    List.Perm (cutProper xs r) xs := by
  unfold cutProper; split <;> first | exact rotL_perm xs r | exact .refl _

theorem length_cutProper (xs : List α) (r : Nat) :
    (cutProper xs r).length = xs.length := by
  unfold cutProper; split <;> first | exact length_rotL xs r | rfl

/-- Deal `m` cards one at a time off the top of `xs` (so they come out
    reversed) and put that packet under the rest. The sudo `deal_under`. -/
def dealUnder (xs : List α) (m : Nat) : List α :=
  xs.drop m ++ (xs.take m).reverse

theorem dealUnder_perm (xs : List α) (m : Nat) :
    List.Perm (dealUnder xs m) xs := by
  unfold dealUnder
  have h1 : List.Perm (xs.drop m ++ (xs.take m).reverse) ((xs.take m).reverse ++ xs.drop m) :=
    List.perm_append_comm
  have h2 : List.Perm ((xs.take m).reverse ++ xs.drop m) (xs.take m ++ xs.drop m) :=
    (List.reverse_perm _).append (.refl _)
  exact (h1.trans h2).trans (by rw [List.take_append_drop])

theorem length_dealUnder (xs : List α) (m : Nat) :
    (dealUnder xs m).length = xs.length :=
  (dealUnder_perm xs m).length_eq

/-- The v12 pile rule shared by the deal, the rank cut and both inverses:
    apply `f` to the hand if `fits hand.length`, else to the key pile if
    `fits key.length`, else leave both piles alone. -/
def onPile (fits : Nat → Prop) [DecidablePred fits] (f : List α → List α)
    (hand key : List α) : List α × List α :=
  if fits hand.length then (f hand, key)
  else if fits key.length then (hand, f key)
  else (hand, key)

section onPile
variable (fits : Nat → Prop) [DecidablePred fits]

theorem onPile_perm (f : List α → List α) (hf : ∀ xs, List.Perm (f xs) xs)
    (hand key : List α) :
    List.Perm ((onPile fits f hand key).1 ++ (onPile fits f hand key).2) (hand ++ key) := by
  unfold onPile
  split
  · exact (hf hand).append (.refl key)
  · split
    · exact (List.Perm.refl hand).append (hf key)
    · exact .refl _

theorem length_onPile_fst (f : List α → List α) (hf : ∀ xs, (f xs).length = xs.length)
    (hand key : List α) : (onPile fits f hand key).1.length = hand.length := by
  unfold onPile
  split
  · exact hf hand
  · split <;> rfl

theorem length_onPile_snd (f : List α → List α) (hf : ∀ xs, (f xs).length = xs.length)
    (hand key : List α) : (onPile fits f hand key).2.length = key.length := by
  unfold onPile
  split
  · rfl
  · split
    · exact hf key
    · rfl

/-- The one inverse lemma: if `f` keeps lengths (so the same branch fires
    again) and `g` undoes `f` whenever `fits` holds, then `onPile fits g` undoes
    `onPile fits f`. Used in both directions for the deal and the cut. -/
theorem onPile_inv (f g : List α → List α) (hlen : ∀ xs, (f xs).length = xs.length)
    (hgf : ∀ xs, fits xs.length → g (f xs) = xs) (hand key : List α) :
    onPile fits g (onPile fits f hand key).1 (onPile fits f hand key).2 = (hand, key) := by
  by_cases hH : fits hand.length
  · have h1 : onPile fits f hand key = (f hand, key) := if_pos hH
    rw [h1]
    have h2 : fits (f hand).length := by rw [hlen]; exact hH
    show (if fits (f hand).length then _ else _) = _
    rw [if_pos h2, hgf hand hH]
  · by_cases hK : fits key.length
    · have h1 : onPile fits f hand key = (hand, f key) := by
        unfold onPile; rw [if_neg hH, if_pos hK]
      rw [h1]
      have h2 : fits (f key).length := by rw [hlen]; exact hK
      show (if fits hand.length then _ else if fits (f key).length then _ else _) = _
      rw [if_neg hH, if_pos h2, hgf key hK]
    · have h1 : onPile fits f hand key = (hand, key) := by
        unfold onPile; rw [if_neg hH, if_neg hK]
      rw [h1]
      show (if fits hand.length then _ else if fits key.length then _ else _) = _
      rw [if_neg hH, if_neg hK]

end onPile

/-- PassKey deal count: suit + 2 (♣0 ♥1 ♠2 ♦3). -/
def dealCount (c : Nat) : Nat := suit c + 2

/-- SPEC §3.7 step 2: deal suit + 2 under the hand if they fit, else under the
    key pile if they fit, else nothing. -/
def maybeDeal (hand key : List Nat) (c : Nat) : List Nat × List Nat :=
  onPile (dealCount c < ·) (dealUnder · (dealCount c)) hand key

theorem maybeDeal_perm (hand key : List Nat) (c : Nat) :
    List.Perm ((maybeDeal hand key c).1 ++ (maybeDeal hand key c).2) (hand ++ key) :=
  onPile_perm _ _ (dealUnder_perm · _) hand key

theorem length_maybeDeal_fst (hand key : List Nat) (c : Nat) :
    (maybeDeal hand key c).1.length = hand.length :=
  length_onPile_fst _ _ (length_dealUnder · _) hand key

theorem length_maybeDeal_snd (hand key : List Nat) (c : Nat) :
    (maybeDeal hand key c).2.length = key.length :=
  length_onPile_snd _ _ (length_dealUnder · _) hand key

/-- SPEC §3.7 step 3: the rank cut on the hand if it fits, else on the key
    pile if it fits, else nothing. -/
def maybeCut (hand key : List Nat) (c : Nat) : List Nat × List Nat :=
  onPile (fun n => 0 < n ∧ rank c < n) (cutProper · (rank c)) hand key

theorem maybeCut_perm (hand key : List Nat) (c : Nat) :
    List.Perm ((maybeCut hand key c).1 ++ (maybeCut hand key c).2) (hand ++ key) :=
  onPile_perm _ _ (cutProper_perm · _) hand key

theorem length_maybeCut_fst (hand key : List Nat) (c : Nat) :
    (maybeCut hand key c).1.length = hand.length :=
  length_onPile_fst _ _ (length_cutProper · _) hand key

theorem length_maybeCut_snd (hand key : List Nat) (c : Nat) :
    (maybeCut hand key c).2.length = key.length :=
  length_onPile_snd _ _ (length_cutProper · _) hand key

/-- One PassKey step after the controller `c` is popped (v12): deal, then the
    rank cut with key-pile fallback, then `c` on top of the key pile. -/
def passKeyStep (hand key : List Nat) (c : Nat) : List Nat × List Nat :=
  let d := maybeDeal hand key c
  let p := maybeCut d.1 d.2 c
  (p.1, c :: p.2)

theorem length_passKeyStep_fst (hand key : List Nat) (c : Nat) :
    (passKeyStep hand key c).1.length = hand.length := by
  simp only [passKeyStep, length_maybeCut_fst, length_maybeDeal_fst]

theorem length_passKeyStep_snd (hand key : List Nat) (c : Nat) :
    (passKeyStep hand key c).2.length = key.length + 1 := by
  simp only [passKeyStep, length_maybeCut_snd, length_maybeDeal_snd, List.length_cons]

theorem passKeyStep_perm (hand key : List Nat) (c : Nat) :
    List.Perm ((passKeyStep hand key c).1 ++ (passKeyStep hand key c).2)
              (c :: hand ++ key) := by
  dsimp [passKeyStep]
  have hr := maybeDeal_perm hand key c
  have hc := maybeCut_perm (maybeDeal hand key c).1 (maybeDeal hand key c).2 c
  have hmid : List.Perm
      ((maybeCut (maybeDeal hand key c).1 (maybeDeal hand key c).2 c).1 ++
        c :: (maybeCut (maybeDeal hand key c).1 (maybeDeal hand key c).2 c).2)
      (c :: ((maybeCut (maybeDeal hand key c).1 (maybeDeal hand key c).2 c).1 ++
        (maybeCut (maybeDeal hand key c).1 (maybeDeal hand key c).2 c).2)) :=
    List.perm_middle
  refine hmid.trans ?_
  refine (hc.cons c).trans ?_
  refine (hr.cons c).trans ?_
  simp [List.cons_append]

/-- Fuel-indexed PassKey recursion (avoids structural-recursion friction). -/
def passKeyGoN : Nat → List Nat → List Nat → List Nat
  | 0, _, key => key
  | _n + 1, [], key => key
  | n + 1, c :: rest, key =>
      let p := passKeyStep rest key c
      passKeyGoN n p.1 p.2

def passToKeyCutFallback (deck : List Nat) : List Nat :=
  passKeyGoN deck.length deck []

theorem passKeyGoN_perm :
    ∀ (n : Nat) (hand key : List Nat),
      hand.length ≤ n →
      List.Perm (passKeyGoN n hand key) (hand ++ key)
  | 0, hand, key, hlen => by
      have : hand = [] := by cases hand <;> simp at hlen ⊢
      subst this; simp [passKeyGoN]
  | n + 1, [], key, _ => by simp [passKeyGoN]
  | n + 1, c :: rest, key, hlen => by
      simp only [passKeyGoN]
      have hs := passKeyStep_perm rest key c
      have hlen' : (passKeyStep rest key c).1.length ≤ n := by
        rw [length_passKeyStep_fst]
        simp at hlen; omega
      have ih := passKeyGoN_perm n (passKeyStep rest key c).1 (passKeyStep rest key c).2 hlen'
      exact ih.trans hs

/-- S3: PassKey preserves card multiset (`List.Perm`). -/
theorem passToKeyCutFallback_perm (deck : List Nat) :
    List.Perm (passToKeyCutFallback deck) deck := by
  simpa [passToKeyCutFallback] using
    passKeyGoN_perm deck.length deck [] (Nat.le_refl _)

theorem passKeyGoN_length (n : Nat) (hand key : List Nat) (h : hand.length ≤ n) :
    (passKeyGoN n hand key).length = hand.length + key.length := by
  have p := passKeyGoN_perm n hand key h
  simpa [List.length_append] using p.length_eq

/-! ## S4: constructive inverse

Each forward step is `maybeDeal` then `maybeCut` then "controller on top of key".
Branching uses only the controller and the two pile lengths, so the same
predicates invert the step. `F` is the composition of those bijections.
-/

def cutProperInv (xs : List α) (r : Nat) : List α :=
  if r < xs.length then rotR xs r else xs

theorem length_cutProperInv (xs : List α) (r : Nat) :
    (cutProperInv xs r).length = xs.length := by
  unfold cutProperInv; split <;> first | exact length_rotR xs r | rfl

theorem cutProperInv_cutProper (xs : List α) (r : Nat) :
    cutProperInv (cutProper xs r) r = xs := by
  unfold cutProper cutProperInv
  split
  · next h =>
    have hlen : (rotL xs r).length = xs.length := length_rotL xs r
    simp only [hlen, h, ↓reduceIte]
    exact rotR_rotL xs r
  · next h =>
    simp only [h, ↓reduceIte]

theorem cutProper_cutProperInv (xs : List α) (r : Nat) :
    cutProper (cutProperInv xs r) r = xs := by
  unfold cutProperInv
  split
  · next h =>
    have hlen : (rotR xs r).length = xs.length := length_rotR xs r
    unfold cutProper
    simp only [hlen, h, ↓reduceIte]
    exact rotL_rotR xs r
  · next h =>
    unfold cutProper
    simp only [h, ↓reduceIte]

/-- Undo `dealUnder`: take the bottom `m` cards and deal them back onto the top.
    The sudo `undeal_under`. -/
def undealUnder (xs : List α) (m : Nat) : List α :=
  (xs.drop (xs.length - m)).reverse ++ xs.take (xs.length - m)

theorem length_undealUnder (xs : List α) (m : Nat) :
    (undealUnder xs m).length = xs.length := by
  unfold undealUnder
  simp only [List.length_append, List.length_reverse, List.length_drop, List.length_take]
  omega

theorem undealUnder_dealUnder (xs : List α) (m : Nat) :
    undealUnder (dealUnder xs m) m = xs := by
  unfold undealUnder
  rw [length_dealUnder]
  unfold dealUnder
  have hd : (xs.drop m).length = xs.length - m := List.length_drop m xs
  have hk : xs.length - m = (xs.drop m).length := hd.symm
  rw [hk, List.drop_left, List.take_left, List.reverse_reverse, List.take_append_drop]

theorem dealUnder_undealUnder (xs : List α) (m : Nat) (h : m ≤ xs.length) :
    dealUnder (undealUnder xs m) m = xs := by
  unfold dealUnder undealUnder
  have hlen : ((xs.drop (xs.length - m)).reverse).length = m := by
    rw [List.length_reverse, List.length_drop]; omega
  have hA : List.drop m ((xs.drop (xs.length - m)).reverse ++ xs.take (xs.length - m)) =
      xs.take (xs.length - m) := by
    exact List.drop_left' hlen
  have hB : List.take m ((xs.drop (xs.length - m)).reverse ++ xs.take (xs.length - m)) =
      (xs.drop (xs.length - m)).reverse := by
    exact List.take_left' hlen
  rw [hA, hB, List.reverse_reverse]
  exact List.take_append_drop _ _

/-- Inverse of `maybeDeal`. Lengths are invariant, so the same predicates fire. -/
def maybeDealInv (hand key : List Nat) (c : Nat) : List Nat × List Nat :=
  onPile (dealCount c < ·) (undealUnder · (dealCount c)) hand key

theorem length_maybeDealInv_fst (hand key : List Nat) (c : Nat) :
    (maybeDealInv hand key c).1.length = hand.length :=
  length_onPile_fst _ _ (length_undealUnder · _) hand key

theorem length_maybeDealInv_snd (hand key : List Nat) (c : Nat) :
    (maybeDealInv hand key c).2.length = key.length :=
  length_onPile_snd _ _ (length_undealUnder · _) hand key

theorem maybeDealInv_maybeDeal (hand key : List Nat) (c : Nat) :
    maybeDealInv (maybeDeal hand key c).1 (maybeDeal hand key c).2 c = (hand, key) :=
  onPile_inv _ _ _ (length_dealUnder · _) (fun xs _ => undealUnder_dealUnder xs _) hand key

theorem maybeDeal_maybeDealInv (hand key : List Nat) (c : Nat) :
    maybeDeal (maybeDealInv hand key c).1 (maybeDealInv hand key c).2 c = (hand, key) :=
  onPile_inv _ _ _ (length_undealUnder · _)
    (fun xs h => dealUnder_undealUnder xs _ (Nat.le_of_lt h)) hand key

/-- Inverse of `maybeCut`. Lengths are invariant, so the same predicates fire. -/
def maybeCutInv (hand key : List Nat) (c : Nat) : List Nat × List Nat :=
  onPile (fun n => 0 < n ∧ rank c < n) (cutProperInv · (rank c)) hand key

theorem length_maybeCutInv_fst (hand key : List Nat) (c : Nat) :
    (maybeCutInv hand key c).1.length = hand.length :=
  length_onPile_fst _ _ (length_cutProperInv · _) hand key

theorem length_maybeCutInv_snd (hand key : List Nat) (c : Nat) :
    (maybeCutInv hand key c).2.length = key.length :=
  length_onPile_snd _ _ (length_cutProperInv · _) hand key

theorem maybeCutInv_maybeCut (hand key : List Nat) (c : Nat) :
    maybeCutInv (maybeCut hand key c).1 (maybeCut hand key c).2 c = (hand, key) :=
  onPile_inv _ _ _ (length_cutProper · _) (fun xs _ => cutProperInv_cutProper xs _) hand key

theorem maybeCut_maybeCutInv (hand key : List Nat) (c : Nat) :
    maybeCut (maybeCutInv hand key c).1 (maybeCutInv hand key c).2 c = (hand, key) :=
  onPile_inv _ _ _ (length_cutProperInv · _) (fun xs _ => cutProper_cutProperInv xs _) hand key

/-- Undo one PassKey step: pop the controller off the key, undo the rank cut,
    undo the deal, put the controller on top of the hand. -/
def invPassKeyStep (hand key : List Nat) : List Nat × List Nat :=
  match key with
  | [] => (hand, [])
  | c :: rest =>
      let p := maybeCutInv hand rest c
      let q := maybeDealInv p.1 p.2 c
      (c :: q.1, q.2)

theorem length_invPassKeyStep_fst (hand : List Nat) (c : Nat) (rest : List Nat) :
    (invPassKeyStep hand (c :: rest)).1.length = hand.length + 1 := by
  simp [invPassKeyStep, length_maybeDealInv_fst, length_maybeCutInv_fst]

theorem length_invPassKeyStep_snd (hand : List Nat) (c : Nat) (rest : List Nat) :
    (invPassKeyStep hand (c :: rest)).2.length = rest.length := by
  simp [invPassKeyStep, length_maybeDealInv_snd, length_maybeCutInv_snd]

theorem undealUnder_perm (xs : List α) (m : Nat) :
    List.Perm (undealUnder xs m) xs := by
  unfold undealUnder
  have h1 : List.Perm ((xs.drop (xs.length - m)).reverse ++ xs.take (xs.length - m))
      (xs.drop (xs.length - m) ++ xs.take (xs.length - m)) :=
    (List.reverse_perm _).append (.refl _)
  have h2 : List.Perm (xs.drop (xs.length - m) ++ xs.take (xs.length - m))
      (xs.take (xs.length - m) ++ xs.drop (xs.length - m)) :=
    List.perm_append_comm
  exact (h1.trans h2).trans (by rw [List.take_append_drop])

theorem cutProperInv_perm (xs : List α) (r : Nat) :
    List.Perm (cutProperInv xs r) xs := by
  unfold cutProperInv; split <;> first | exact rotR_perm xs r | exact .refl _

theorem maybeDealInv_perm (hand key : List Nat) (c : Nat) :
    List.Perm ((maybeDealInv hand key c).1 ++ (maybeDealInv hand key c).2) (hand ++ key) :=
  onPile_perm _ _ (undealUnder_perm · _) hand key

theorem maybeCutInv_perm (hand key : List Nat) (c : Nat) :
    List.Perm ((maybeCutInv hand key c).1 ++ (maybeCutInv hand key c).2) (hand ++ key) :=
  onPile_perm _ _ (cutProperInv_perm · _) hand key

/-- One inverse step moves cards between piles only. -/
theorem invPassKeyStep_perm (hand : List Nat) (c : Nat) (rest : List Nat) :
    List.Perm ((invPassKeyStep hand (c :: rest)).1 ++ (invPassKeyStep hand (c :: rest)).2)
      (hand ++ c :: rest) := by
  simp only [invPassKeyStep, List.cons_append]
  have h := (maybeDealInv_perm (maybeCutInv hand rest c).1 (maybeCutInv hand rest c).2 c).trans
    (maybeCutInv_perm hand rest c)
  exact (h.cons c).trans List.perm_middle.symm

/-- Per-step left inverse: invert after `passKeyStep` recovers `(c :: hand, key)`. -/
theorem invPassKeyStep_passKeyStep (hand key : List Nat) (c : Nat) :
    invPassKeyStep (passKeyStep hand key c).1 (passKeyStep hand key c).2
      = (c :: hand, key) := by
  simp only [passKeyStep]
  change invPassKeyStep
      (maybeCut (maybeDeal hand key c).1 (maybeDeal hand key c).2 c).1
      (c :: (maybeCut (maybeDeal hand key c).1 (maybeDeal hand key c).2 c).2) =
    (c :: hand, key)
  simp only [invPassKeyStep]
  have hc := maybeCutInv_maybeCut (maybeDeal hand key c).1 (maybeDeal hand key c).2 c
  have hd := maybeDealInv_maybeDeal hand key c
  simp [hc, hd]

/-- Per-step right inverse on a nonempty key pile `c :: rest`. -/
theorem passKeyStep_invPassKeyStep (hand : List Nat) (c : Nat) (rest : List Nat) :
    passKeyStep
        (maybeDealInv (maybeCutInv hand rest c).1 (maybeCutInv hand rest c).2 c).1
        (maybeDealInv (maybeCutInv hand rest c).1 (maybeCutInv hand rest c).2 c).2 c
      = (hand, c :: rest) := by
  simp only [passKeyStep]
  have hd := maybeDeal_maybeDealInv (maybeCutInv hand rest c).1 (maybeCutInv hand rest c).2 c
  have hc := maybeCut_maybeCutInv hand rest c
  simp [hd, hc]

/-- Fuel-indexed inverse walk (key pile shrinks). -/
def passKeyInvGoN : Nat → List Nat → List Nat → List Nat
  | 0, _, hand => hand
  | _n + 1, [], hand => hand
  | n + 1, c :: rest, hand =>
      let p := invPassKeyStep hand (c :: rest)
      passKeyInvGoN n p.2 p.1

def passToKeyCutFallbackInv (out : List Nat) : List Nat :=
  passKeyInvGoN out.length out []

theorem passKeyInvGoN_length :
    ∀ (n : Nat) (key hand : List Nat),
      key.length ≤ n →
      (passKeyInvGoN n key hand).length = key.length + hand.length
  | 0, key, hand, hlen => by
      have : key = [] := by cases key <;> simp at hlen ⊢
      subst this; simp [passKeyInvGoN]
  | n + 1, [], hand, _ => by simp [passKeyInvGoN]
  | n + 1, c :: rest, hand, hlen => by
      simp only [passKeyInvGoN]
      have hlen' : (invPassKeyStep hand (c :: rest)).2.length ≤ n := by
        rw [length_invPassKeyStep_snd]
        simp [List.length_cons] at hlen; omega
      have ih := passKeyInvGoN_length n (invPassKeyStep hand (c :: rest)).2
        (invPassKeyStep hand (c :: rest)).1 hlen'
      rw [ih, length_invPassKeyStep_snd, length_invPassKeyStep_fst]
      simp [List.length_cons]; omega

theorem passKeyInvGoN_cons (c : Nat) (rest hand : List Nat) :
    passKeyInvGoN (c :: rest).length (c :: rest) hand =
      let p := invPassKeyStep hand (c :: rest)
      passKeyInvGoN rest.length p.2 p.1 :=
  rfl

/-- Lifting the per-step left inverse: inverting the finished key recovers `hand`. -/
theorem passKeyInvGoN_passKeyGoN :
    ∀ (n : Nat) (hand key : List Nat),
      hand.length ≤ n →
      passKeyInvGoN (hand.length + key.length) (passKeyGoN n hand key) [] =
        passKeyInvGoN key.length key hand
  | 0, hand, key, hlen => by
      have : hand = [] := by cases hand <;> simp at hlen ⊢
      subst this
      simp [passKeyGoN]
  | n + 1, [], key, _ => by
      simp [passKeyGoN]
  | n + 1, c :: rest, key, hlen => by
      simp only [passKeyGoN]
      have hlen' : (passKeyStep rest key c).1.length ≤ n := by
        rw [length_passKeyStep_fst]
        simp [List.length_cons] at hlen; omega
      have ih := passKeyInvGoN_passKeyGoN n
        (passKeyStep rest key c).1 (passKeyStep rest key c).2 hlen'
      have hfuel :
          (c :: rest).length + key.length =
            (passKeyStep rest key c).1.length + (passKeyStep rest key c).2.length := by
        rw [length_passKeyStep_fst, length_passKeyStep_snd]
        simp [List.length_cons]; omega
      rw [hfuel, ih]
      -- p.2 is `c :: kAfter`; invert that cons
      let kAfter := (maybeCut (maybeDeal rest key c).1 (maybeDeal rest key c).2 c).2
      have hcons : (passKeyStep rest key c).2 = c :: kAfter := rfl
      rw [hcons, passKeyInvGoN_cons]
      have hinv : invPassKeyStep (passKeyStep rest key c).1 (c :: kAfter) =
          (c :: rest, key) := by
        simpa [hcons] using invPassKeyStep_passKeyStep rest key c
      rw [hinv]
      simp [kAfter, length_maybeCut_snd, length_maybeDeal_snd]

/-- Lifting the per-step right inverse. -/
theorem passKeyGoN_passKeyInvGoN :
    ∀ (n : Nat) (key hand : List Nat),
      key.length ≤ n →
      passKeyGoN (hand.length + key.length) (passKeyInvGoN n key hand) [] =
        passKeyGoN hand.length hand key
  | 0, key, hand, hlen => by
      have : key = [] := by cases key <;> simp at hlen ⊢
      subst this
      simp [passKeyInvGoN]
  | n + 1, [], hand, _ => by
      simp [passKeyInvGoN]
  | n + 1, c :: rest, hand, hlen => by
      simp only [passKeyInvGoN]
      have hlen' : (invPassKeyStep hand (c :: rest)).2.length ≤ n := by
        rw [length_invPassKeyStep_snd]
        simp at hlen; omega
      have ih := passKeyGoN_passKeyInvGoN n
        (invPassKeyStep hand (c :: rest)).2
        (invPassKeyStep hand (c :: rest)).1 hlen'
      have hfuel :
          hand.length + (c :: rest).length =
            (invPassKeyStep hand (c :: rest)).1.length +
              (invPassKeyStep hand (c :: rest)).2.length := by
        rw [length_invPassKeyStep_fst, length_invPassKeyStep_snd]
        simp; omega
      rw [hfuel, ih]
      -- go one reconstructed controller, then the right-inverse step
      have hstep := passKeyStep_invPassKeyStep hand c rest
      simp only [invPassKeyStep] at hstep ⊢
      -- (invPassKeyStep hand (c::rest)).1 = c :: (maybeDealInv ...).1
      -- passKeyGoN on that cons unfolds
      change passKeyGoN
          (c :: (maybeDealInv (maybeCutInv hand rest c).1 (maybeCutInv hand rest c).2 c).1).length
          (c :: (maybeDealInv (maybeCutInv hand rest c).1 (maybeCutInv hand rest c).2 c).1)
          (maybeDealInv (maybeCutInv hand rest c).1 (maybeCutInv hand rest c).2 c).2 =
        passKeyGoN hand.length hand (c :: rest)
      simp only [passKeyGoN]
      have hlenh :
          (maybeDealInv (maybeCutInv hand rest c).1 (maybeCutInv hand rest c).2 c).1.length =
            hand.length := by
        rw [length_maybeDealInv_fst, length_maybeCutInv_fst]
      rw [hlenh, hstep]

/-- S4: `F_inv ∘ F = id`. -/
theorem passToKeyCutFallback_leftInverse (d : List Nat) :
    passToKeyCutFallbackInv (passToKeyCutFallback d) = d := by
  unfold passToKeyCutFallbackInv passToKeyCutFallback
  have hlen : (passKeyGoN d.length d []).length = d.length := by
    simpa using passKeyGoN_length d.length d [] (Nat.le_refl _)
  rw [hlen]
  have h := passKeyInvGoN_passKeyGoN d.length d [] (Nat.le_refl _)
  simpa [passKeyInvGoN] using h

/-- S4: `F ∘ F_inv = id`. -/
theorem passToKeyCutFallback_rightInverse (d : List Nat) :
    passToKeyCutFallback (passToKeyCutFallbackInv d) = d := by
  unfold passToKeyCutFallback passToKeyCutFallbackInv
  have hlen : (passKeyInvGoN d.length d []).length = d.length := by
    simpa using passKeyInvGoN_length d.length d [] (Nat.le_refl _)
  rw [show (passKeyInvGoN d.length d []).length = d.length + 0 from by
        simpa using passKeyInvGoN_length d.length d [] (Nat.le_refl _)]
  have h := passKeyGoN_passKeyInvGoN d.length d [] (Nat.le_refl _)
  simpa [passKeyGoN] using h

theorem passKey_leftInverse :
    LeftInverse passToKeyCutFallbackInv passToKeyCutFallback :=
  passToKeyCutFallback_leftInverse

theorem passKey_rightInverse :
    RightInverse passToKeyCutFallbackInv passToKeyCutFallback :=
  passToKeyCutFallback_rightInverse

/-- S4: PassKey is injective on lists (hence on \(S_{52}\)). -/
theorem passKey_injective {d₁ d₂ : List Nat}
    (h : passToKeyCutFallback d₁ = passToKeyCutFallback d₂) : d₁ = d₂ := by
  rw [← passToKeyCutFallback_leftInverse d₁, ← passToKeyCutFallback_leftInverse d₂, h]

end DoubleDeal
