"""Witness tables (and their Lean boilerplate) for the theorem that no NONTRIVIAL
AFFINE relabelling is covariant for the unkeyed v12 round body F = GridCycle o stem,
for any output relabelling tau: `CovariantAffine.roundBody_not_covariant_affine`
(heavy library).

Affine relabellings: c = (rank index r = c % 13, GF(4) suit label l) ->
(u r + a mod 13, A l xor x) with u = k + 1 in Z13* (k = 0..11) and A in GL(2,2)
(g = 0..5, cell0lib.GL_MATS, g = 0 the identity). In Lean: `v10Sym a x * linSym k g`.
There are 3744 parameter tuples (the maps are pairwise distinct: Lean
`affine_params_inj`); the 3692 with (k, g) != (0, 0) are the ones outside v10Sym.
They form the normalizer of v10Sym in Sym(52) (true by the holomorph count, not a Lean
theorem). Covariance of v10Sym a x * L reduces to the seat-26 condition for the
linear part L = linSym k g alone (v10Sym commutes with stem), so one witness per
(k, g): EXHAUSTIVE over the 71 nontrivial (k, g). Not a proof by itself: the heavy
Lean library re-checks every table entry by kernel decide!, so a wrong entry fails
the heavy build.

The tables of linSym (glTab, glInvTab, unitInvTab) are emitted into
CovariantAffineLists.lean from cell0lib.py, so the Lean maps and the Python maps
searched here are the same data (`--check` compares them). The witness search is
shared with ../v12-covariant/cell0_witness.py (cell0lib.py); the pairs used here are
part of the Lean list `cell0Pairs` written by that script.

Usage:
    python3 aff_witness.py           # print the table
    python3 aff_witness.py --lean    # write the Lean files and the log
    python3 aff_witness.py --check   # CI: fail if a Lean file or the log is stale

--lean writes
  security/DoubleDealSecurity/CovariantAffineLists.lean (glTab, glInvTab, unitInvTab, affW),
  security/DoubleDealSecurityHeavy/CovariantAffineChecks.lean (check_lin_k_g, lin_checks_all),
  aff_witness.log (the printed output).
"""
import contextlib
import io
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
SEC = HERE.parents[1] / 'security'
sys.path.insert(0, str(HERE.parent / 'v12-covariant'))
sys.path.insert(0, str(REPO / 'tools'))
import cell0lib as C  # noqa: E402
from gencheck import parser, emit  # noqa: E402

LISTS_OUT = SEC / 'DoubleDealSecurity' / 'CovariantAffineLists.lean'
CHECKS_OUT = SEC / 'DoubleDealSecurityHeavy' / 'CovariantAffineChecks.lean'
LOG_OUT = HERE / 'aff_witness.log'
FIX = 'python3 proofs/doubledeal/analysis/v12-primenonswap/aff_witness.py --lean'


def table():
    """(c, number of candidate pairs, affW with entry 0 unused, sorted used pairs,
    cell0Pairs). affW is indexed by 6 k + g."""
    c, ncand, _, aff, pairs = C.tables()
    return c, ncand, [pairs[0]] + aff, sorted(set(aff)), pairs


def report(t):
    c, ncand, tab, used, pairs = t
    print(f'g(identity deck) = {c}; single position swaps (i, j) keeping g: {ncand} of 1326')
    print(f'witness found for all 71 nontrivial linear parts (k, g); position pairs used: {used}')
    print(f'(all in cell0Pairs = {pairs})')
    print(f'glTab = {C.GL_TAB}; glInvTab = {C.GL_INV}; unitInvTab = {C.UNIT_INV}')
    for n in range(1, 72):
        k, g = divmod(n, 6)
        print(f'  u = {k + 1:2d} (k = {k:2d}), g = {g}: swap {tab[n]}')
    print('affW =', tab)


def lists_text(tab):
    return f'''/-
  GENERATED by proofs/doubledeal/analysis/v12-primenonswap/aff_witness.py --lean;
  do not edit (CI: `aff_witness.py --check`).

  The tables of `CovariantAffine.linSym` (from `analysis/v12-covariant/cell0lib.py`,
  the same data the witness search uses), and the witness seat pairs for
  `CovariantAffine.linCheck`: for the linear part `(k, g)` (`(k, g) ≠ (0, 0)`),
  `affW[6 k + g] = (i, j)` names the deck `posSwapDeck i j` (the identity deck with
  seats `i`, `j` exchanged); every pair is in `CovariantNarrow.cell0Pairs`. Entry 0
  of `affW` is unused (set to the first pair of `cell0Pairs`). These lists are data,
  not trusted: Lean proves the tables give inverse bijections and linear maps
  (`linFn_left`, `linFn_right`, `glApp_gfAdd`), and the heavy library checks every
  witness by kernel `decide!` (`cell0PairsCheck_ok`, `check_lin_*`).
-/
namespace DoubleDeal.Security.CovariantAffine

/-- GL(2,2) on GF(4) labels `0..3` (bit 0 = `l % 2`, bit 1 = `l / 2`): row `g` lists
    the images of labels 0, 1, 2, 3. Row 0 is the identity. -/
def glTab : List (List Nat) :=
  {C.GL_TAB}

/-- `glInvTab[g]`: the index of the inverse matrix of row `g`. -/
def glInvTab : List (Fin 6) :=
  {C.GL_INV}

/-- `unitInvTab[k] = k'` with `(k + 1)(k' + 1) ≡ 1 (mod 13)`. -/
def unitInvTab : List (Fin 12) :=
  {C.UNIT_INV}

/-- The witness seat pair for each linear part, at index `6 k + g` (entry 0 unused). -/
def affW : List (Fin 52 × Fin 52) :=
  {C.fmt(tab)}

end DoubleDeal.Security.CovariantAffine
'''


def checks_text():
    ns = range(1, 72)
    thms = ''.join(
        f'/-- (PROVED, kernel `decide!`) The check for `(k, g) = ({n // 6}, {n % 6})`. -/\n'
        f'theorem check_lin_{n // 6}_{n % 6} : linCheck {n // 6} {n % 6} = true := by decide!\n'
        for n in ns)
    cases = ''.join(f'  | ⟨{n // 6}, _⟩, ⟨{n % 6}, _⟩, _ => check_lin_{n // 6}_{n % 6}\n' for n in ns)
    return f'''/-
  GENERATED by proofs/doubledeal/analysis/v12-primenonswap/aff_witness.py --lean;
  do not edit (CI: `aff_witness.py --check`).

  HEAVY: one kernel `decide!` per nontrivial linear part `(k, g)` of check B of
  `AffChecks` (`DoubleDealSecurity/CovariantAffine.lean`), two stem evaluations each.
  One theorem per `(k, g)` because kernel memory is released between declarations but
  grows with the number of stem evaluations inside one `decide!`.
-/
import DoubleDealSecurity.CovariantAffine

namespace DoubleDeal.Security.CovariantAffine

{thms}
/-- (PROVED) Check B for every `(k, g) ≠ (0, 0)`. -/
theorem lin_checks_all : ∀ (k : Fin 12) (g : Fin 6), (k, g) ≠ (0, 0) → linCheck k g = true
  | ⟨0, _⟩, ⟨0, _⟩, h => absurd rfl h
{cases}  | ⟨k + 12, h⟩, _, _ => absurd h (by omega)
  | _, ⟨g + 6, h⟩, _ => absurd h (by omega)

end DoubleDeal.Security.CovariantAffine
'''


def main():
    args = cli.parse_args()
    t = table()
    if not (args.lean or args.check):
        report(t)
        return 0
    tab = t[2]
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        report(t)
    rc = 0
    for path, text in ((LISTS_OUT, lists_text(tab)), (CHECKS_OUT, checks_text()),
                       (LOG_OUT, buf.getvalue())):
        rc |= emit(path, text, args.check, fix=FIX)
    return rc


cli = parser(__doc__)
cli.add_argument('--lean', action='store_true',
                 help='write the Lean files and the log (see the module docstring)')

if __name__ == '__main__':
    sys.exit(main())
