"""Witness tables (and their Lean boilerplate) for the theorem that no AFFINE
relabelling with a nontrivial linear part is covariant for the unkeyed v12 round
body F = GridCycle o stem, for any output relabelling tau:
`CovariantAffine.roundBody_not_covariant_affine` (heavy library).

Affine relabellings: c = (rank r, GF(4) suit label l) -> (u r + a mod 13, A l + x)
with u in Z13* (u = k + 1, k = 0..11) and A in GL(2,2) (g = 0..5, table GL_TAB,
g = 0 the identity). In Lean: `v10Sym a x * linSym k g`. They are the 3744 elements
of the normalizer of v10Sym in Sym(52) (v10Sym = the 52 translations); the 3692 with
(k, g) != (0, 0) are the ones outside v10Sym. Covariance of v10Sym a x * L reduces to
the seat-26 condition for the linear part L = linSym k g alone (v10Sym commutes with
stem), so one witness per (k, g): EXHAUSTIVE over the 71 nontrivial (k, g). Not a
proof by itself: the heavy Lean library re-checks every table entry by kernel
decide!, so a wrong entry fails the heavy build.

Witness: m1 = identity deck, m2 = identity deck with seats i, j exchanged, with
g(m1) = g(m2) (g = stem cell 0) but g(L.m1) != g(L.m2). Same argument as
`../v12-covariant/cell0_witness.py`.

Usage:
    python3 aff_witness.py           # print the table
    python3 aff_witness.py --lean    # write the Lean files and the log
    python3 aff_witness.py --check   # CI: fail if a Lean file or the log is stale

--lean writes
  security/DoubleDealSecurity/CovariantAffineLists.lean (affPairs, affW),
  security/DoubleDealSecurityHeavy/CovariantAffineChecks.lean (check_lin_k_g, lin_checks_all),
  aff_witness.log (the printed output).
"""
import contextlib
import io
import itertools
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
SEC = HERE.parents[1] / 'security'
sys.path.insert(0, str(SEC / 'checks'))
sys.path.insert(0, str(REPO / 'tools'))
import ddport as P  # noqa: E402
from gencheck import parser, emit  # noqa: E402

V = 12
LISTS_OUT = SEC / 'DoubleDealSecurity' / 'CovariantAffineLists.lean'
CHECKS_OUT = SEC / 'DoubleDealSecurityHeavy' / 'CovariantAffineChecks.lean'
LOG_OUT = HERE / 'aff_witness.log'
FIX = 'python3 proofs/doubledeal/analysis/v12-primenonswap/aff_witness.py --lean'

# GL(2,2) on GF(4) labels 0..3 (bit 0 = l % 2, bit 1 = l // 2); same table as
# `CovariantAffine.glTab`. Row g = images of labels 0, 1, 2, 3.
GL_TAB = [[0, 1, 2, 3], [0, 2, 1, 3], [0, 1, 3, 2], [0, 3, 2, 1], [0, 2, 3, 1], [0, 3, 1, 2]]


def lin(k, g):
    """linSym k g as an image list: rank * (k + 1) mod 13, label -> GL_TAB[g][label]."""
    return [13 * P.SUIT_OF_LABEL[GL_TAB[g][P.LABEL[c // 13]]] + ((k + 1) * (c % 13)) % 13
            for c in range(52)]


def sanity():
    for row in GL_TAB:  # linear, bijective, and the 6 rows are distinct
        assert row[0] == 0 and row[3] == row[1] ^ row[2] and sorted(row) == [0, 1, 2, 3]
    assert len({tuple(r) for r in GL_TAB}) == 6
    for k in range(12):
        for g in range(6):
            s = lin(k, g)
            assert sorted(s) == list(range(52))
            assert (s == list(range(52))) == ((k, g) == (0, 0))


def gfun(m):
    return P.stem(m, V)[0]


def pos_swap(i, j):
    d = list(range(52))
    d[i], d[j] = d[j], d[i]
    return d


def table():
    """(c, number of candidate pairs, affW with entry 0 unused, sorted used pairs).
    affW is indexed by 6 k + g."""
    idd = list(range(52))
    c = gfun(idd)
    cands = [(i, j) for i, j in itertools.combinations(range(52), 2)
             if gfun(pos_swap(i, j)) == c]
    tab = [(1, 2)]  # entry 0 unused ((k, g) = (0, 0) is the identity)
    for n in range(1, 72):
        k, g = divmod(n, 6)
        s = lin(k, g)
        v1 = gfun([s[x] for x in idd])
        for i, j in cands:
            if gfun([s[x] for x in pos_swap(i, j)]) != v1:
                tab.append((i, j))
                break
        else:
            raise SystemExit(f'no witness for (k, g) = {(k, g)}')
    used = sorted(set(tab[1:]))
    for i, j in used:
        assert gfun(pos_swap(i, j)) == c
    return c, len(cands), tab, used


def report(t):
    c, ncand, tab, used = t
    print(f'g(identity deck) = {c}; single position swaps (i, j) keeping g: {ncand} of 1326')
    print(f'witness found for all 71 nontrivial linear parts (k, g); position pairs used: {used}')
    for n in range(1, 72):
        k, g = divmod(n, 6)
        print(f'  u = {k + 1:2d} (k = {k:2d}), g = {g}: swap {tab[n]}')
    print('affW =', tab)


def fmt(ps):
    rows = [', '.join(f'({i}, {j})' for i, j in ps[k:k + 8]) for k in range(0, len(ps), 8)]
    return '[' + ',\n    '.join(rows) + ']'


def lists_text(tab, used):
    return f'''/-
  GENERATED by proofs/doubledeal/analysis/v12-primenonswap/aff_witness.py --lean;
  do not edit (CI: `aff_witness.py --check`).

  Witness seat pairs for `CovariantAffine.linCheck`: for the linear part `(k, g)`
  (`(k, g) ≠ (0, 0)`), `affW[6 k + g] = (i, j)` names the deck `posSwapDeck i j` (the
  identity deck with seats `i`, `j` exchanged). `affPairs` lists the {len(used)} pairs used.
  Entry 0 of `affW` is unused. These lists are data, not trusted: the heavy library
  checks every entry by kernel `decide!` (`affPairsCheck_ok`, `check_lin_*`), so a
  wrong entry fails the heavy build.
-/
namespace DoubleDeal.Security.CovariantAffine

/-- The seat pairs used by `affW` (each keeps stem cell 0 of the identity deck). -/
def affPairs : List (Fin 52 × Fin 52) :=
  {fmt(used)}

/-- The witness seat pair for each linear part, at index `6 k + g` (entry 0 unused). -/
def affW : List (Fin 52 × Fin 52) :=
  {fmt(tab)}

end DoubleDeal.Security.CovariantAffine
'''


def checks_text():
    ns = range(1, 72)
    thms = ''.join(
        f'/-- (PROVED, kernel `decide!`) The check for `(k, g) = ({n // 6}, {n % 6})`. -/\n'
        f'theorem check_lin_{n // 6}_{n % 6} : linCheck {n // 6} {n % 6} = true := by decide!\n'
        for n in ns)
    cases = ''.join(f'  | ⟨{n // 6}, _⟩, ⟨{n % 6}, _⟩, _ => check_lin_{n // 6}_{n % 6}\n' for n in ns)
    return f'''/-
  GENERATED by proofs/doubledeal/analysis/v12-primenonswap/aff_witness.py --lean;
  do not edit (CI: `aff_witness.py --check`).

  HEAVY: one kernel `decide!` per nontrivial linear part `(k, g)` of check B of
  `AffChecks` (`DoubleDealSecurity/CovariantAffine.lean`), two stem evaluations each.
  One theorem per `(k, g)` because kernel memory is released between declarations but
  grows with the number of stem evaluations inside one `decide!`.
-/
import DoubleDealSecurity.CovariantAffine

namespace DoubleDeal.Security.CovariantAffine

{thms}
/-- (PROVED) Check B for every `(k, g) ≠ (0, 0)`. -/
theorem lin_checks_all : ∀ (k : Fin 12) (g : Fin 6), (k, g) ≠ (0, 0) → linCheck k g = true
  | ⟨0, _⟩, ⟨0, _⟩, h => absurd rfl h
{cases}  | ⟨k + 12, h⟩, _, _ => absurd h (by omega)
  | _, ⟨g + 6, h⟩, _ => absurd h (by omega)

end DoubleDeal.Security.CovariantAffine
'''


def main():
    args = cli.parse_args()
    sanity()
    t = table()
    if not (args.lean or args.check):
        report(t)
        return 0
    _, _, tab, used = t
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        report(t)
    rc = 0
    for path, text in ((LISTS_OUT, lists_text(tab, used)), (CHECKS_OUT, checks_text()),
                       (LOG_OUT, buf.getvalue())):
        rc |= emit(path, text, args.check, fix=FIX)
    return rc


cli = parser(__doc__)
cli.add_argument('--lean', action='store_true',
                 help='write the Lean files and the log (see the module docstring)')

if __name__ == '__main__':
    sys.exit(main())
