"""Write DoubleDealV10/WitnessData.lean from ../witness_v10.json (deprecated v10 only).
usage: python3 witness_to_lean.py [--check]"""
import json, sys
from pathlib import Path
here = Path(__file__).resolve().parent
w = json.loads((here.parent / 'witness_v10.json').read_text())
L = lambda xs: '[' + ', '.join(map(str, xs)) + ']'
text = f'''/-
  Generated by proofs/deprecated/doubledeal-v10/lean/witness_to_lean.py from
  ../witness_v10.json. Do not hand-edit; re-run the script (CI runs --check).
  Single-deck GridCycle witness data for deprecated DoubleDeal v10 only.
-/
namespace DoubleDealV10.Witness

/-- Card values as the emitted code sees them (`Int` array). -/
def embed (xs : List Nat) : Array Int := Array.mk (xs.map Int.ofNat)

/-- The two card ids swapped by sigma (K♣ = {w["sigma"][0]}, K♦ = {w["sigma"][1]}). -/
def sigmaA : Nat := {w["sigma"][0]}
def sigmaB : Nat := {w["sigma"][1]}

/-- sigma on card ids. -/
def sw (x : Nat) : Nat := if x = sigmaA then sigmaB else if x = sigmaB then sigmaA else x

/-- The input packet of GridCycle (walk order). -/
def deck : List Nat := {L(w["deck"])}
/-- The emitted v10 `mix_columns` of `deck`, as recorded in the JSON. -/
def mix : List Nat := {L(w["mix"])}
/-- As recorded in the JSON: sigma applied to `deck`. -/
def deckSigmaJson : List Nat := {L(w["deck_sigma"])}
/-- As recorded in the JSON: `mix_columns` of sigma applied to `deck`. -/
def mixSigmaJson : List Nat := {L(w["mix_sigma"])}

end DoubleDealV10.Witness
'''
p = here / 'DoubleDealV10' / 'WitnessData.lean'
if '--check' in sys.argv:
    assert p.read_text() == text, 'WitnessData.lean is stale; re-run witness_to_lean.py'
    print('OK WitnessData.lean matches witness_v10.json')
else:
    p.parent.mkdir(exist_ok=True); p.write_text(text); print('wrote', p)
