/-
  Generated by proofs/megadreifach/vectors/json_to_lean.py from
  primitives/hash/megadreifach/kats/megaminx_hash_kats.json. Do not hand-edit
  (CI runs the script with --check).

  Pins the statement of every KAT theorem in Kat.lean: for each vector, the
  elaborated type of `MegaDreifach.Link2.Kat.kat_<name>` must be, syntactically
  (`=ₛ`), `Megadreifach.v_Hash (embed (hexBytes vec_<name>.msgHex)) =
  .ok (embed (hexBytes vec_<name>.digestHex))` over the real constants (every name
  `_root_`-qualified). A local `def Vectors.vec_*`, `hexBytes`, `embed` or
  `Megadreifach.v_Hash` in Kat.lean (or an imported module) changes the constants
  in that type and fails the build of this module. Built with the heavy library
  (`lake build MegaDreifachHeavy`); planted negatives:
  proofs/megadreifach/vectors/katspec_negatives.py.
-/
import MegaDreifachHeavy.Kat

#guard_expr type_of% @_root_.MegaDreifach.Link2.Kat.kat_empty =ₛ
  @_root_.Eq (_root_.Except _root_.SudoRt.Trap (_root_.Array _root_.Int))
    (_root_.Megadreifach.v_Hash (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.msgHex _root_.MegaDreifach.Vectors.vec_empty))))
    (@_root_.Except.ok _root_.SudoRt.Trap (_root_.Array _root_.Int) (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.digestHex _root_.MegaDreifach.Vectors.vec_empty))))

#guard_expr type_of% @_root_.MegaDreifach.Link2.Kat.kat_short_abc =ₛ
  @_root_.Eq (_root_.Except _root_.SudoRt.Trap (_root_.Array _root_.Int))
    (_root_.Megadreifach.v_Hash (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.msgHex _root_.MegaDreifach.Vectors.vec_short_abc))))
    (@_root_.Except.ok _root_.SudoRt.Trap (_root_.Array _root_.Int) (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.digestHex _root_.MegaDreifach.Vectors.vec_short_abc))))

#guard_expr type_of% @_root_.MegaDreifach.Link2.Kat.kat_short_one =ₛ
  @_root_.Eq (_root_.Except _root_.SudoRt.Trap (_root_.Array _root_.Int))
    (_root_.Megadreifach.v_Hash (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.msgHex _root_.MegaDreifach.Vectors.vec_short_one))))
    (@_root_.Except.ok _root_.SudoRt.Trap (_root_.Array _root_.Int) (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.digestHex _root_.MegaDreifach.Vectors.vec_short_one))))

#guard_expr type_of% @_root_.MegaDreifach.Link2.Kat.kat_edge_27 =ₛ
  @_root_.Eq (_root_.Except _root_.SudoRt.Trap (_root_.Array _root_.Int))
    (_root_.Megadreifach.v_Hash (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.msgHex _root_.MegaDreifach.Vectors.vec_edge_27))))
    (@_root_.Except.ok _root_.SudoRt.Trap (_root_.Array _root_.Int) (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.digestHex _root_.MegaDreifach.Vectors.vec_edge_27))))

#guard_expr type_of% @_root_.MegaDreifach.Link2.Kat.kat_edge_28 =ₛ
  @_root_.Eq (_root_.Except _root_.SudoRt.Trap (_root_.Array _root_.Int))
    (_root_.Megadreifach.v_Hash (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.msgHex _root_.MegaDreifach.Vectors.vec_edge_28))))
    (@_root_.Except.ok _root_.SudoRt.Trap (_root_.Array _root_.Int) (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.digestHex _root_.MegaDreifach.Vectors.vec_edge_28))))

#guard_expr type_of% @_root_.MegaDreifach.Link2.Kat.kat_edge_29 =ₛ
  @_root_.Eq (_root_.Except _root_.SudoRt.Trap (_root_.Array _root_.Int))
    (_root_.Megadreifach.v_Hash (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.msgHex _root_.MegaDreifach.Vectors.vec_edge_29))))
    (@_root_.Except.ok _root_.SudoRt.Trap (_root_.Array _root_.Int) (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.digestHex _root_.MegaDreifach.Vectors.vec_edge_29))))

#guard_expr type_of% @_root_.MegaDreifach.Link2.Kat.kat_multi_56 =ₛ
  @_root_.Eq (_root_.Except _root_.SudoRt.Trap (_root_.Array _root_.Int))
    (_root_.Megadreifach.v_Hash (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.msgHex _root_.MegaDreifach.Vectors.vec_multi_56))))
    (@_root_.Except.ok _root_.SudoRt.Trap (_root_.Array _root_.Int) (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.digestHex _root_.MegaDreifach.Vectors.vec_multi_56))))

#guard_expr type_of% @_root_.MegaDreifach.Link2.Kat.kat_multi_100 =ₛ
  @_root_.Eq (_root_.Except _root_.SudoRt.Trap (_root_.Array _root_.Int))
    (_root_.Megadreifach.v_Hash (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.msgHex _root_.MegaDreifach.Vectors.vec_multi_100))))
    (@_root_.Except.ok _root_.SudoRt.Trap (_root_.Array _root_.Int) (_root_.MegaDreifach.Link2.embed (_root_.MegaDreifach.hexBytes (_root_.MegaDreifach.Vectors.HashVec.digestHex _root_.MegaDreifach.Vectors.vec_multi_100))))
