// Re-checks the Scramble vectors and the recorded attack results through the JavaScript
// that sudoc generates from primitives/hash/scramble/scramble.sudo (the normative
// definition), not through the fast attack engine scramble_ref.py.
//
//   SUDOC=/path/to/sudoc node scramble_sudo_check.mjs
//
// SUDOC defaults to <repo>/.sudocode/sudoc/target/release/sudoc, as in
// tools/generate-demos.sh. The build is the same `sudoc build --target js` that
// tools/build.sh uses for the demo, written to a temporary directory. This script only
// runs things: it reads SPEC.md (the 10 vectors) and logs/ (the attack messages) and
// changes neither. Exit status 0 iff every check passes.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const sudo = join(root, "primitives/hash/scramble/scramble.sudo");
const spec = join(root, "primitives/hash/scramble/SPEC.md");
const sudoc = process.env.SUDOC || join(root, ".sudocode/sudoc/target/release/sudoc");

const out = mkdtempSync(join(tmpdir(), "scramble-sudo-check-"));
let failed = 0;
try {
    execFileSync(sudoc, ["build", "--target", "js", "-o", out, sudo], { stdio: ["ignore", "ignore", "inherit"] });
    const gen = await import(pathToFileURL(join(out, "scramble.mjs")).href);
    console.log("[0] JS generated by sudoc from primitives/hash/scramble/scramble.sudo");

    const run = (version, bytes) => {
        const s = version === 2 ? gen.scramble_v2() : gen.scramble_v1();
        gen.update(s, [...bytes]);
        const r = gen.evaluate(s);
        const hex = r.digest.map((b) => b.toString(16).padStart(2, "0")).join("").toUpperCase().slice(1);
        return { hex, steps: r.trace.length, facelets: r.trace[r.trace.length - 1].facelets };
    };
    const check = (label, ok, detail) => {
        if (!ok) failed++;
        console.log(`  ${ok ? "ok  " : "FAIL"} ${label}${detail ? ": " + detail : ""}`);
    };

    // [1] The 10 vectors, read from the SPEC's scramble_v1 and scramble_v2 tables.
    console.log("[1] SPEC vectors (digest, step count, final facelets)");
    let version = 0, rows = 0;
    for (const line of readFileSync(spec, "utf8").split("\n")) {
        if (/^## /.test(line)) version = line === "## scramble_v1" ? 1 : line === "## scramble_v2" ? 2 : 0;
        const m = version && line.match(/^\| (empty|`([^`]*)`|byte `([0-9A-F]{2})`) \| (\d+) \| `([0-9A-F]{17})` \| `([WYROBG]{54})` \|$/);
        if (!m) continue;
        const bytes = m[1] === "empty" ? [] : m[3] ? [parseInt(m[3], 16)] : [...Buffer.from(m[2], "utf8")];
        const got = run(version, bytes);
        const ok = got.hex === m[5] && got.steps === Number(m[4]) && got.facelets === m[6];
        check(`v${version} ${m[1]}`, ok, ok ? m[5] : JSON.stringify(got));
        rows++;
    }
    check("vector count", rows === 10, `${rows}/10`);

    // [2] The attack results recorded in logs/, hashed with the generated scramble_v2.
    console.log("[2] attack results from logs/ (scramble_v2)");
    const log = (name) => readFileSync(join(here, "logs", name), "utf8");
    const grab = (text, re) => {
        const m = text.match(re);
        if (!m) throw new Error(`pattern ${re} not found`);
        return Buffer.from(m[1], "hex");
    };
    const coll = log("scramble_collision.log");
    const m1 = grab(coll, /^ {2}m1 = ([0-9a-f]+)$/m), m2 = grab(coll, /^ {2}m2 = ([0-9a-f]+)$/m);
    const d1 = run(2, m1).hex, d2 = run(2, m2).hex;
    check(`collision: m1 != m2, ${m1.length} + ${m2.length} bytes`, !m1.equals(m2) && m1.length === 88 && m2.length === 88);
    check("collision: digest(m1)", d1 === "0AFB0BE3439EF6892", d1);
    check("collision: digest(m2)", d2 === "0AFB0BE3439EF6892", d2);
    const sec = log("scramble_second_preimage.log");
    const tgt = grab(sec, /target message ([0-9a-f]+)$/m), msp = grab(sec, /found M = ([0-9a-f]+) /);
    const dt = run(2, tgt).hex, ds = run(2, msp).hex;
    check(`second preimage: M != target, ${msp.length} bytes`, !msp.equals(tgt) && msp.length === 172);
    check("second preimage: digest(target)", dt === "0A38700830D1C599C", dt);
    check("second preimage: digest(M)", ds === "0A38700830D1C599C", ds);
    const pre = log("scramble_decode_preimage.log");
    const mp = grab(pre, /found M = ([0-9a-f]+) /);
    const dp = run(2, mp).hex;
    check(`hex-only preimage: ${mp.length} bytes`, mp.length === 172);
    check("hex-only preimage: digest(M)", dp === "132FDCE0BF26E5898", dp);
} finally {
    rmSync(out, { recursive: true, force: true });
}
console.log(failed ? `FAILED: ${failed} check(s)` : "ALL OK");
process.exit(failed ? 1 : 0);
