#!/usr/bin/env python3
"""Write DoubleDealSecurity/V8Vectors.lean from the frozen v8 vectors (--check: compare)."""
import json, sys
from pathlib import Path
PKG = Path(__file__).resolve().parents[1]
REPO = PKG.parents[2]
sys.path.insert(0, str(REPO / 'tools'))
from gencheck import parser, emit
args = parser(__doc__).parse_args()
V = {v['name']: v for v in json.loads((REPO / 'proofs/deprecated/doubledeal-v8/vectors/doubledeal_v8_vectors.json').read_text())['vectors']}
def L(x): return '[' + ', '.join(map(str, x)) + ']'
out = ['''/-
  Fidelity of the proof-only v8 model (`V8.mixColumns`, `sumRanksV8`,
  `V8.unkeyedNoMix`) against the frozen v8 known-answer vectors
  (proofs/deprecated/doubledeal-v8/vectors/doubledeal_v8_vectors.json).
  Generated by checks/gen_v8_vectors.py. Kernel-checked with `decide!`.
-/
import DoubleDealSecurity.GridCycle

namespace DoubleDeal.Security.V8Vectors

open DoubleDeal DoubleDeal.Security

def ofL (l : List Nat) : Fin 52 → Nat := fun i => l.getD i.val 0
''']
for n in ['mix_columns_identity', 'mix_columns_reverse', 'mix_columns_mul17']:
    v = V[n]; out.append(f"theorem {n} : List.ofFn (V8.mixColumns (ofL {L(v['input'])})) =\n    {L(v['output'])} := by decide!\n")
v = V['sum_ranks_mul17']
out.append(f"theorem sum_ranks_mul17 : List.ofFn (scoopColumnMajor (sumRanksV8 (layColumnMajor (ofL {L(v['input'])})))) =\n    {L(v['output'])} := by decide!\n")
for n in ['unkeyed_full_identity', 'unkeyed_full_reverse', 'unkeyed_full_mul17']:
    v = V[n]; out.append(f"theorem {n} : List.ofFn (V8.mixColumns (V8.unkeyedNoMix (ofL {L(v['input'])}))) =\n    {L(v['output'])} := by decide!\n")
out.append("end DoubleDeal.Security.V8Vectors\n")
text = '\n'.join(out)
dst = PKG / 'DoubleDealSecurity/V8Vectors.lean'
sys.exit(emit(dst, text, args.check))
