#!/usr/bin/env python3
"""Emit proofs/twodeck/lean/TwoDeck/Vectors.lean from twodeck_vectors.json.

Do not hand-copy decks into Lean. Regenerated by regen.sh (or this script
alone when the JSON is already current).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_JSON = HERE / "twodeck_vectors.json"
DEFAULT_LEAN = HERE.parent / "lean" / "TwoDeck" / "Vectors.lean"

HEADER = """/-
  Generated by proofs/twodeck/vectors/json_to_lean.py from twodeck_vectors.json.
  Do not hand-edit. Re-run proofs/twodeck/vectors/regen.sh after sudo changes.
-/
namespace TwoDeck.Vectors

"""

FOOTER = """
end TwoDeck.Vectors
"""


def lean_list(xs: list[int]) -> str:
    return "[" + ", ".join(str(int(x)) for x in xs) + "]"


def lean_list_of_lists(xss: list[list[int]]) -> str:
    inner = ",\n    ".join(lean_list(xs) for xs in xss)
    return "[\n    " + inner + "\n  ]"


def emit(doc: dict) -> str:
    vectors = doc["vectors"]
    by_kind: dict[str, list[dict]] = {}
    for v in vectors:
        by_kind.setdefault(v["kind"], []).append(v)

    parts = [HEADER]
    parts.append(f"/-- {doc.get('note', '').replace('/-', '/ -')} -/\n")
    parts.append(f"def schema : Nat := {int(doc.get('schema', 1))}\n")
    parts.append(f"def vectorCount : Nat := {len(vectors)}\n")

    # Shared decks used by several kinds — emit named constants for the
    # first encrypt vector so comments can point at the published KAT.
    for v in vectors:
        if v["name"] == "encrypt_published":
            parts.append("\n/-- Published encrypt/decrypt KAT from twodeck.sudo. -/\n")
            parts.append(f"def publishedMessage : List Nat := {lean_list(v['message'])}\n")
            parts.append(f"def publishedKey : List Nat := {lean_list(v['key'])}\n")
            parts.append(f"def publishedCipher : List Nat := {lean_list(v['cipher'])}\n")
            break

    kind_emitters = {
        "encrypt": emit_encrypt,
        "passkey": emit_unary,
        "expand_keys": emit_expand,
        "counter_deck": emit_counter,
        "mix_columns": emit_unary,
        "sum_ranks": emit_unary,
        "shift_rows": emit_unary,
        "unkeyed_full": emit_unary,
        "compose": emit_compose,
        "ctr_encrypt": emit_ctr,
    }
    unknown = set(by_kind) - set(kind_emitters)
    if unknown:
        raise SystemExit(f"unknown vector kinds: {sorted(unknown)}")

    for kind, fn in kind_emitters.items():
        items = by_kind.get(kind, [])
        if items:
            parts.append(fn(kind, items))

    parts.append(FOOTER)
    return "".join(parts)


def emit_encrypt(_kind: str, items: list[dict]) -> str:
    lines = [
        "\nstructure EncryptVec where\n",
        "  name : String\n",
        "  message : List Nat\n",
        "  key : List Nat\n",
        "  cipher : List Nat\n",
        "\ndef encryptVecs : List EncryptVec := [\n",
    ]
    for i, v in enumerate(items):
        comma = "," if i + 1 < len(items) else ""
        lines.append(
            "  { name := "
            + json.dumps(v["name"])
            + f",\n    message := {lean_list(v['message'])},\n"
            f"    key := {lean_list(v['key'])},\n"
            f"    cipher := {lean_list(v['cipher'])} }}{comma}\n"
        )
    lines.append("]\n")
    return "".join(lines)


def emit_unary(kind: str, items: list[dict]) -> str:
    struct = {
        "passkey": "PassKeyVec",
        "mix_columns": "MixColumnsVec",
        "sum_ranks": "SumRanksVec",
        "shift_rows": "ShiftRowsVec",
        "unkeyed_full": "UnkeyedFullVec",
    }[kind]
    list_name = {
        "passkey": "passkeyVecs",
        "mix_columns": "mixColumnsVecs",
        "sum_ranks": "sumRanksVecs",
        "shift_rows": "shiftRowsVecs",
        "unkeyed_full": "unkeyedFullVecs",
    }[kind]
    lines = [
        f"\nstructure {struct} where\n",
        "  name : String\n",
        "  input : List Nat\n",
        "  output : List Nat\n",
        f"\ndef {list_name} : List {struct} := [\n",
    ]
    for i, v in enumerate(items):
        comma = "," if i + 1 < len(items) else ""
        lines.append(
            "  { name := "
            + json.dumps(v["name"])
            + f",\n    input := {lean_list(v['input'])},\n"
            f"    output := {lean_list(v['output'])} }}{comma}\n"
        )
    lines.append("]\n")
    return "".join(lines)


def emit_expand(_kind: str, items: list[dict]) -> str:
    lines = [
        "\nstructure ExpandKeysVec where\n",
        "  name : String\n",
        "  k0 : List Nat\n",
        "  keys : List (List Nat)\n",
        "\ndef expandKeysVecs : List ExpandKeysVec := [\n",
    ]
    for i, v in enumerate(items):
        comma = "," if i + 1 < len(items) else ""
        lines.append(
            "  { name := "
            + json.dumps(v["name"])
            + f",\n    k0 := {lean_list(v['k0'])},\n"
            f"    keys := {lean_list_of_lists(v['keys'])} }}{comma}\n"
        )
    lines.append("]\n")
    return "".join(lines)


def emit_counter(_kind: str, items: list[dict]) -> str:
    lines = [
        "\nstructure CounterDeckVec where\n",
        "  name : String\n",
        "  nonce : List Nat\n",
        "  index : Nat\n",
        "  deck : List Nat\n",
        "\ndef counterDeckVecs : List CounterDeckVec := [\n",
    ]
    for i, v in enumerate(items):
        comma = "," if i + 1 < len(items) else ""
        lines.append(
            "  { name := "
            + json.dumps(v["name"])
            + f",\n    nonce := {lean_list(v['nonce'])},\n"
            f"    index := {int(v['index'])},\n"
            f"    deck := {lean_list(v['deck'])} }}{comma}\n"
        )
    lines.append("]\n")
    return "".join(lines)


def emit_compose(_kind: str, items: list[dict]) -> str:
    lines = [
        "\nstructure ComposeVec where\n",
        "  name : String\n",
        "  message : List Nat\n",
        "  key : List Nat\n",
        "  output : List Nat\n",
        "\ndef composeVecs : List ComposeVec := [\n",
    ]
    for i, v in enumerate(items):
        comma = "," if i + 1 < len(items) else ""
        lines.append(
            "  { name := "
            + json.dumps(v["name"])
            + f",\n    message := {lean_list(v['message'])},\n"
            f"    key := {lean_list(v['key'])},\n"
            f"    output := {lean_list(v['output'])} }}{comma}\n"
        )
    lines.append("]\n")
    return "".join(lines)


def emit_ctr(_kind: str, items: list[dict]) -> str:
    lines = [
        "\nstructure CtrEncryptVec where\n",
        "  name : String\n",
        "  blocks : List (List Nat)\n",
        "  key : List Nat\n",
        "  nonce : List Nat\n",
        "  output : List (List Nat)\n",
        "\ndef ctrEncryptVecs : List CtrEncryptVec := [\n",
    ]
    for i, v in enumerate(items):
        comma = "," if i + 1 < len(items) else ""
        lines.append(
            "  { name := "
            + json.dumps(v["name"])
            + f",\n    blocks := {lean_list_of_lists(v['blocks'])},\n"
            f"    key := {lean_list(v['key'])},\n"
            f"    nonce := {lean_list(v['nonce'])},\n"
            f"    output := {lean_list_of_lists(v['output'])} }}{comma}\n"
        )
    lines.append("]\n")
    return "".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--json", type=Path, default=DEFAULT_JSON)
    p.add_argument("--lean", type=Path, default=DEFAULT_LEAN)
    p.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the Lean file does not match a fresh emit (no write)",
    )
    args = p.parse_args()
    doc = json.loads(args.json.read_text())
    text = emit(doc)
    if args.check:
        current = args.lean.read_text() if args.lean.exists() else ""
        if current != text:
            print(
                f"{args.lean} is stale; run proofs/twodeck/vectors/regen.sh "
                "or json_to_lean.py",
                file=sys.stderr,
            )
            return 1
        print(f"{args.lean} matches {args.json}")
        return 0
    args.lean.parent.mkdir(parents=True, exist_ok=True)
    args.lean.write_text(text)
    print(f"wrote {args.lean} ({doc.get('schema')} schema, {len(doc['vectors'])} vectors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
