"""Pick the single-deck GridCycle witness for the deprecated v10 write-up (analysis only).

Finds, with a fixed seed, a deck d on which the transposition sigma = K♣↔K♦ (card ids 12 and 51)
commutes with v10 GridCycle, GC(sigma d) = sigma GC(d), with both cards away from the always-surviving
tail (walk positions < 40), and writes ../witness_v10.json. Uses sudoc's Python output of the
frozen v10 sudo (proofs/sudo_py.py).
usage: python3 make_witness.py [--check]"""
import json, random, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[2]))
import sudo_py
V = sudo_py.doubledeal(10)
sys.path.insert(0, str(sudo_py.REPO / 'tools'))
from gencheck import parser, emit
args = parser(__doc__).parse_args()

A, B = 12, 51
sw = lambda xs: [B if x == A else A if x == B else x for x in xs]

def find(seed=10):
    rng = random.Random(seed)
    tries = 0
    while True:
        tries += 1
        d = list(range(52)); rng.shuffle(d)
        if max(d.index(A), d.index(B)) >= 40: continue
        out = V.mix_columns(d)
        if V.mix_columns(sw(d)) == sw(out):
            return d, out, tries

d, out, tries = find()
w = {
    "note": "Deprecated DoubleDeal v10 GridCycle (mix_columns) single-deck witness: sigma = K♣↔K♦ commutes on this deck. "
            "Per-layer evidence only; not an attack on the full cipher. Generated by attack/make_witness.py (seed 10).",
    "sigma": [A, B],
    "deck": d,
    "mix": out,
    "deck_sigma": sw(d),
    "mix_sigma": sw(out),
    "walk_positions": [d.index(A), d.index(B)],
    "random_decks_tried": tries,
}
text = json.dumps(w, indent=1) + "\n"
path = HERE.parent / 'witness_v10.json'
if not args.check:
    print('positions', w['walk_positions'], 'tries', tries)
sys.exit(emit(path, text, args.check))
