#!/usr/bin/env python3
"""Emit DoubleDealV9/WitnessData.lean from ../witness_v9.json.

Do not hand-copy the witness into Lean. Same pattern as the v8 package: `--check`
fails (for CI) when the committed Lean differs from what this script would write.
The round keys and stage states are hints from the JSON; the Lean kernel re-checks
each of them against the emitted `Doubledeal_v9` functions.

Usage: python3 witness_to_lean.py [--check]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
JSON_PATH = HERE.parent / "witness_v9.json"
LEAN_PATH = HERE / "DoubleDealV9" / "WitnessData.lean"
sys.path.insert(0, str(HERE.parents[3] / "tools"))
from gencheck import parser, emit  # noqa: E402


def lean_list(xs: list[int]) -> str:
    return "[" + ", ".join(str(int(x)) for x in xs) + "]"


def is_perm(xs: list[int]) -> bool:
    return sorted(xs) == list(range(52))


def check_doc(doc: dict) -> None:
    for name in ("key", "message", "cipher", "message_sigma", "cipher_sigma"):
        if not is_perm(doc[name]):
            raise SystemExit(f"witness_v9.json: {name} is not a permutation of 0..51")
    h = doc["hints"]
    if len(h["round_keys"]) != 6 or len(h["states"]) != 7 or len(h["states_sigma"]) != 7:
        raise SystemExit("witness_v9.json: hints need 6 round keys and 7 states per run")
    for xs in h["round_keys"] + h["states"] + h["states_sigma"]:
        if not is_perm(xs):
            raise SystemExit("witness_v9.json: a hint is not a permutation of 0..51")
    s = doc["sigma"]
    if len(s) != 2 or s[0] == s[1]:
        raise SystemExit("witness_v9.json: sigma must be two distinct card ids")
    if h["states"][-1] != doc["cipher"] or h["states_sigma"][-1] != doc["cipher_sigma"]:
        raise SystemExit("witness_v9.json: last hint state must be the recorded cipher")


def emit_text(doc: dict) -> str:
    check_doc(doc)
    x, y = (int(t) for t in doc["sigma"])
    h = doc["hints"]
    keys = "\n".join(f"def K{i + 1} : Array Int := embed {lean_list(k)}" for i, k in enumerate(h["round_keys"]))
    sa = "\n".join(f"def A{i} : Array Int := embed {lean_list(s)}" for i, s in enumerate(h["states"][:-1]))
    sb = "\n".join(f"def B{i} : Array Int := embed {lean_list(s)}" for i, s in enumerate(h["states_sigma"][:-1]))
    return f"""/-
  Generated by proofs/deprecated/doubledeal-v9/lean/witness_to_lean.py from
  ../witness_v9.json. Do not hand-edit; re-run the script (CI runs --check).
  VULNERABILITY PROOF data for deprecated DoubleDeal v9 only.
-/
namespace DoubleDealV9.Witness

/-- Card values as the emitted code sees them (`Int` array). -/
def embed (xs : List Nat) : Array Int := Array.mk (xs.map Int.ofNat)

/-- The two card ids swapped by sigma (K♣ = 12, Q♥ = 24). -/
def sigmaA : Nat := {x}
def sigmaB : Nat := {y}

def key : List Nat := {lean_list(doc["key"])}
def message : List Nat := {lean_list(doc["message"])}
def cipher : List Nat := {lean_list(doc["cipher"])}
/-- As recorded in the JSON: sigma applied to `message`. -/
def messageSigmaJson : List Nat := {lean_list(doc["message_sigma"])}
/-- As recorded in the JSON: E_K(sigma M). -/
def cipherSigmaJson : List Nat := {lean_list(doc["cipher_sigma"])}

/-! Hints (checked by the kernel in `Keys`, `RunM`, `RunSigma`). -/

/-- Round keys K1..K6 (K0 is `key`). -/
{keys}

/-- Deck after whitening (A0), full rounds 1-5 (A1..A5), for `message`. -/
{sa}

/-- The same stages for `messageSigmaJson`. -/
{sb}

end DoubleDealV9.Witness
"""


def main() -> int:
    args = parser(__doc__).parse_args()
    return emit(LEAN_PATH, emit_text(json.loads(JSON_PATH.read_text())), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
