#!/usr/bin/env python3
"""Emit DoubleDealV8/WitnessData.lean from ../witness_v8.json.

Do not hand-copy the witness into Lean. Same pattern as
proofs/doubledeal/vectors/json_to_lean.py: `--check` fails (for CI) when the
committed Lean differs from what this script would write.

Usage: python3 witness_to_lean.py [--check]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
JSON_PATH = HERE.parent / "witness_v8.json"
LEAN_PATH = HERE / "DoubleDealV8" / "WitnessData.lean"


def lean_list(xs: list[int]) -> str:
    return "[" + ", ".join(str(int(x)) for x in xs) + "]"


def check_doc(doc: dict) -> None:
    for name in ("key", "message", "cipher", "message_tau", "cipher_tau"):
        xs = doc[name]
        if sorted(xs) != list(range(52)):
            raise SystemExit(f"witness_v8.json: {name} is not a permutation of 0..51")
    tau = doc["tau"]
    if len(tau) != 2 or tau[0] == tau[1]:
        raise SystemExit("witness_v8.json: tau must be two distinct card ids")


def emit(doc: dict) -> str:
    check_doc(doc)
    x, y = (int(t) for t in doc["tau"])
    return f"""/-
  Generated by proofs/deprecated/doubledeal-v8/lean/witness_to_lean.py from
  ../witness_v8.json. Do not hand-edit; re-run the script (CI runs --check).
  VULNERABILITY PROOF data for deprecated DoubleDeal v8 only.
-/
namespace DoubleDealV8.Witness

/-- The two card ids swapped by tau. -/
def tauA : Nat := {x}
def tauB : Nat := {y}

def key : List Nat := {lean_list(doc["key"])}
def message : List Nat := {lean_list(doc["message"])}
def cipher : List Nat := {lean_list(doc["cipher"])}
/-- As recorded in the JSON: tau applied to `message`. -/
def messageTauJson : List Nat := {lean_list(doc["message_tau"])}
/-- As recorded in the JSON: E_K(tau M). -/
def cipherTauJson : List Nat := {lean_list(doc["cipher_tau"])}

end DoubleDealV8.Witness
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed Lean is stale")
    args = ap.parse_args()
    text = emit(json.loads(JSON_PATH.read_text()))
    if args.check:
        have = LEAN_PATH.read_text() if LEAN_PATH.exists() else ""
        if have != text:
            print(f"{LEAN_PATH} is stale relative to {JSON_PATH}; re-run witness_to_lean.py",
                  file=sys.stderr)
            return 1
        print(f"ok {LEAN_PATH.name} matches {JSON_PATH.name}")
        return 0
    LEAN_PATH.write_text(text)
    print(f"wrote {LEAN_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
