/-
  Generated by proofs/deprecated/doubledeal-v10/lean/witness_to_lean.py from
  ../witness_v10.json. Do not hand-edit; re-run the script (CI runs --check).
  Single-deck GridCycle witness data for deprecated DoubleDeal v10 only.
-/
namespace DoubleDealV10.Witness

/-- Card values as the emitted code sees them (`Int` array). -/
def embed (xs : List Nat) : Array Int := Array.mk (xs.map Int.ofNat)

/-- The two card ids swapped by sigma (K♣ = 12, K♦ = 51). -/
def sigmaA : Nat := 12
def sigmaB : Nat := 51

/-- sigma on card ids. -/
def sw (x : Nat) : Nat := if x = sigmaA then sigmaB else if x = sigmaB then sigmaA else x

/-- The input packet of GridCycle (walk order). -/
def deck : List Nat := [32, 23, 6, 21, 13, 31, 9, 37, 16, 22, 30, 19, 38, 41, 25, 51, 17, 50, 39, 2, 36, 15, 28, 20, 12, 45, 5, 33, 29, 14, 18, 40, 34, 10, 44, 26, 42, 27, 47, 4, 24, 46, 11, 43, 3, 49, 7, 0, 8, 1, 48, 35]
/-- The emitted v10 `mix_columns` of `deck`, as recorded in the JSON. -/
def mix : List Nat := [12, 33, 51, 18, 20, 26, 49, 23, 5, 2, 46, 34, 37, 30, 45, 9, 17, 47, 6, 11, 0, 39, 40, 27, 15, 21, 32, 28, 25, 4, 43, 44, 42, 10, 13, 50, 29, 16, 38, 36, 14, 22, 48, 7, 19, 35, 1, 24, 31, 3, 8, 41]
/-- As recorded in the JSON: sigma applied to `deck`. -/
def deckSigmaJson : List Nat := [32, 23, 6, 21, 13, 31, 9, 37, 16, 22, 30, 19, 38, 41, 25, 12, 17, 50, 39, 2, 36, 15, 28, 20, 51, 45, 5, 33, 29, 14, 18, 40, 34, 10, 44, 26, 42, 27, 47, 4, 24, 46, 11, 43, 3, 49, 7, 0, 8, 1, 48, 35]
/-- As recorded in the JSON: `mix_columns` of sigma applied to `deck`. -/
def mixSigmaJson : List Nat := [51, 33, 12, 18, 20, 26, 49, 23, 5, 2, 46, 34, 37, 30, 45, 9, 17, 47, 6, 11, 0, 39, 40, 27, 15, 21, 32, 28, 25, 4, 43, 44, 42, 10, 13, 50, 29, 16, 38, 36, 14, 22, 48, 7, 19, 35, 1, 24, 31, 3, 8, 41]

end DoubleDealV10.Witness
