/-
  GENERATED by proofs/doubledeal/analysis/v12-covariant/cell0_witness.py --lean;
  do not edit (CI: `cell0_witness.py --check`).

  HEAVY: check A (`pairsCheck cell0Pairs`, shared by `Cov0Checks` and
  `CovariantAffine.AffChecks`) as one kernel `decide!` per pair, and one kernel
  `decide!` per representative `e` of check B of `Cov0Checks`
  (`DoubleDealSecurity/CovariantNarrow.lean`); two stem evaluations each. One theorem
  per pair or `e` because kernel memory is released between declarations but grows
  with the number of stem evaluations inside one `decide!`.
-/
import DoubleDealSecurity.CovariantNarrow

namespace DoubleDeal.Security.CovariantNarrow

/-- (PROVED, kernel `decide!`) Check A for the pair `(1, 2)`. -/
theorem pair_ok_1_2 : g0 (posSwapDeck 1 2) = g0 idDeck := by decide!
/-- (PROVED, kernel `decide!`) Check A for the pair `(1, 3)`. -/
theorem pair_ok_1_3 : g0 (posSwapDeck 1 3) = g0 idDeck := by decide!
/-- (PROVED, kernel `decide!`) Check A for the pair `(1, 5)`. -/
theorem pair_ok_1_5 : g0 (posSwapDeck 1 5) = g0 idDeck := by decide!
/-- (PROVED, kernel `decide!`) Check A for the pair `(1, 8)`. -/
theorem pair_ok_1_8 : g0 (posSwapDeck 1 8) = g0 idDeck := by decide!
/-- (PROVED, kernel `decide!`) Check A for the pair `(1, 12)`. -/
theorem pair_ok_1_12 : g0 (posSwapDeck 1 12) = g0 idDeck := by decide!
/-- (PROVED, kernel `decide!`) Check A for the pair `(1, 34)`. -/
theorem pair_ok_1_34 : g0 (posSwapDeck 1 34) = g0 idDeck := by decide!

/-- (PROVED) Check A: every pair of `cell0Pairs` keeps stem cell 0 of the identity
    deck. -/
theorem cell0PairsCheck_ok : pairsCheck cell0Pairs = true := by
  simp only [pairsCheck, cell0Pairs, List.all_cons, List.all_nil, pair_ok_1_2, pair_ok_1_3, pair_ok_1_5, pair_ok_1_8, pair_ok_1_12, pair_ok_1_34,
    beq_self_eq_true, Bool.and_self]

/-- (PROVED, kernel `decide!`) The check for `e = 1`. -/
theorem check_e1 : cov0Check ⟨1, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 2`. -/
theorem check_e2 : cov0Check ⟨2, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 3`. -/
theorem check_e3 : cov0Check ⟨3, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 4`. -/
theorem check_e4 : cov0Check ⟨4, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 5`. -/
theorem check_e5 : cov0Check ⟨5, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 6`. -/
theorem check_e6 : cov0Check ⟨6, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 7`. -/
theorem check_e7 : cov0Check ⟨7, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 8`. -/
theorem check_e8 : cov0Check ⟨8, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 9`. -/
theorem check_e9 : cov0Check ⟨9, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 10`. -/
theorem check_e10 : cov0Check ⟨10, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 11`. -/
theorem check_e11 : cov0Check ⟨11, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 12`. -/
theorem check_e12 : cov0Check ⟨12, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 13`. -/
theorem check_e13 : cov0Check ⟨13, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 14`. -/
theorem check_e14 : cov0Check ⟨14, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 15`. -/
theorem check_e15 : cov0Check ⟨15, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 16`. -/
theorem check_e16 : cov0Check ⟨16, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 17`. -/
theorem check_e17 : cov0Check ⟨17, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 18`. -/
theorem check_e18 : cov0Check ⟨18, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 19`. -/
theorem check_e19 : cov0Check ⟨19, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 20`. -/
theorem check_e20 : cov0Check ⟨20, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 21`. -/
theorem check_e21 : cov0Check ⟨21, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 22`. -/
theorem check_e22 : cov0Check ⟨22, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 23`. -/
theorem check_e23 : cov0Check ⟨23, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 24`. -/
theorem check_e24 : cov0Check ⟨24, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 25`. -/
theorem check_e25 : cov0Check ⟨25, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 26`. -/
theorem check_e26 : cov0Check ⟨26, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 27`. -/
theorem check_e27 : cov0Check ⟨27, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 28`. -/
theorem check_e28 : cov0Check ⟨28, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 29`. -/
theorem check_e29 : cov0Check ⟨29, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 30`. -/
theorem check_e30 : cov0Check ⟨30, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 31`. -/
theorem check_e31 : cov0Check ⟨31, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 32`. -/
theorem check_e32 : cov0Check ⟨32, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 33`. -/
theorem check_e33 : cov0Check ⟨33, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 34`. -/
theorem check_e34 : cov0Check ⟨34, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 35`. -/
theorem check_e35 : cov0Check ⟨35, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 36`. -/
theorem check_e36 : cov0Check ⟨36, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 37`. -/
theorem check_e37 : cov0Check ⟨37, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 38`. -/
theorem check_e38 : cov0Check ⟨38, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 39`. -/
theorem check_e39 : cov0Check ⟨39, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 40`. -/
theorem check_e40 : cov0Check ⟨40, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 41`. -/
theorem check_e41 : cov0Check ⟨41, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 42`. -/
theorem check_e42 : cov0Check ⟨42, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 43`. -/
theorem check_e43 : cov0Check ⟨43, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 44`. -/
theorem check_e44 : cov0Check ⟨44, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 45`. -/
theorem check_e45 : cov0Check ⟨45, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 46`. -/
theorem check_e46 : cov0Check ⟨46, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 47`. -/
theorem check_e47 : cov0Check ⟨47, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 48`. -/
theorem check_e48 : cov0Check ⟨48, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 49`. -/
theorem check_e49 : cov0Check ⟨49, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 50`. -/
theorem check_e50 : cov0Check ⟨50, by decide⟩ = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `e = 51`. -/
theorem check_e51 : cov0Check ⟨51, by decide⟩ = true := by decide!

/-- (PROVED) Check B for every `e ≠ 0`. -/
theorem checks_all : ∀ e : Fin 52, e ≠ 0 → cov0Check e = true
  | ⟨0, _⟩, h => absurd rfl h
  | ⟨1, _⟩, _ => check_e1
  | ⟨2, _⟩, _ => check_e2
  | ⟨3, _⟩, _ => check_e3
  | ⟨4, _⟩, _ => check_e4
  | ⟨5, _⟩, _ => check_e5
  | ⟨6, _⟩, _ => check_e6
  | ⟨7, _⟩, _ => check_e7
  | ⟨8, _⟩, _ => check_e8
  | ⟨9, _⟩, _ => check_e9
  | ⟨10, _⟩, _ => check_e10
  | ⟨11, _⟩, _ => check_e11
  | ⟨12, _⟩, _ => check_e12
  | ⟨13, _⟩, _ => check_e13
  | ⟨14, _⟩, _ => check_e14
  | ⟨15, _⟩, _ => check_e15
  | ⟨16, _⟩, _ => check_e16
  | ⟨17, _⟩, _ => check_e17
  | ⟨18, _⟩, _ => check_e18
  | ⟨19, _⟩, _ => check_e19
  | ⟨20, _⟩, _ => check_e20
  | ⟨21, _⟩, _ => check_e21
  | ⟨22, _⟩, _ => check_e22
  | ⟨23, _⟩, _ => check_e23
  | ⟨24, _⟩, _ => check_e24
  | ⟨25, _⟩, _ => check_e25
  | ⟨26, _⟩, _ => check_e26
  | ⟨27, _⟩, _ => check_e27
  | ⟨28, _⟩, _ => check_e28
  | ⟨29, _⟩, _ => check_e29
  | ⟨30, _⟩, _ => check_e30
  | ⟨31, _⟩, _ => check_e31
  | ⟨32, _⟩, _ => check_e32
  | ⟨33, _⟩, _ => check_e33
  | ⟨34, _⟩, _ => check_e34
  | ⟨35, _⟩, _ => check_e35
  | ⟨36, _⟩, _ => check_e36
  | ⟨37, _⟩, _ => check_e37
  | ⟨38, _⟩, _ => check_e38
  | ⟨39, _⟩, _ => check_e39
  | ⟨40, _⟩, _ => check_e40
  | ⟨41, _⟩, _ => check_e41
  | ⟨42, _⟩, _ => check_e42
  | ⟨43, _⟩, _ => check_e43
  | ⟨44, _⟩, _ => check_e44
  | ⟨45, _⟩, _ => check_e45
  | ⟨46, _⟩, _ => check_e46
  | ⟨47, _⟩, _ => check_e47
  | ⟨48, _⟩, _ => check_e48
  | ⟨49, _⟩, _ => check_e49
  | ⟨50, _⟩, _ => check_e50
  | ⟨51, _⟩, _ => check_e51
  | ⟨n + 52, h⟩, _ => absurd h (by omega)

end DoubleDeal.Security.CovariantNarrow
