/-
  GENERATED by proofs/doubledeal/analysis/v12-primenonswap/aff_witness.py --lean;
  do not edit (CI: `aff_witness.py --check`).

  HEAVY: one kernel `decide!` per nontrivial linear part `(k, g)` of check B of
  `AffChecks` (`DoubleDealSecurity/CovariantAffine.lean`), two stem evaluations each.
  One theorem per `(k, g)` because kernel memory is released between declarations but
  grows with the number of stem evaluations inside one `decide!`.
-/
import DoubleDealSecurity.CovariantAffine

namespace DoubleDeal.Security.CovariantAffine

/-- (PROVED, kernel `decide!`) The check for `(k, g) = (0, 1)`. -/
theorem check_lin_0_1 : linCheck 0 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (0, 2)`. -/
theorem check_lin_0_2 : linCheck 0 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (0, 3)`. -/
theorem check_lin_0_3 : linCheck 0 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (0, 4)`. -/
theorem check_lin_0_4 : linCheck 0 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (0, 5)`. -/
theorem check_lin_0_5 : linCheck 0 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (1, 0)`. -/
theorem check_lin_1_0 : linCheck 1 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (1, 1)`. -/
theorem check_lin_1_1 : linCheck 1 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (1, 2)`. -/
theorem check_lin_1_2 : linCheck 1 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (1, 3)`. -/
theorem check_lin_1_3 : linCheck 1 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (1, 4)`. -/
theorem check_lin_1_4 : linCheck 1 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (1, 5)`. -/
theorem check_lin_1_5 : linCheck 1 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (2, 0)`. -/
theorem check_lin_2_0 : linCheck 2 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (2, 1)`. -/
theorem check_lin_2_1 : linCheck 2 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (2, 2)`. -/
theorem check_lin_2_2 : linCheck 2 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (2, 3)`. -/
theorem check_lin_2_3 : linCheck 2 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (2, 4)`. -/
theorem check_lin_2_4 : linCheck 2 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (2, 5)`. -/
theorem check_lin_2_5 : linCheck 2 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (3, 0)`. -/
theorem check_lin_3_0 : linCheck 3 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (3, 1)`. -/
theorem check_lin_3_1 : linCheck 3 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (3, 2)`. -/
theorem check_lin_3_2 : linCheck 3 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (3, 3)`. -/
theorem check_lin_3_3 : linCheck 3 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (3, 4)`. -/
theorem check_lin_3_4 : linCheck 3 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (3, 5)`. -/
theorem check_lin_3_5 : linCheck 3 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (4, 0)`. -/
theorem check_lin_4_0 : linCheck 4 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (4, 1)`. -/
theorem check_lin_4_1 : linCheck 4 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (4, 2)`. -/
theorem check_lin_4_2 : linCheck 4 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (4, 3)`. -/
theorem check_lin_4_3 : linCheck 4 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (4, 4)`. -/
theorem check_lin_4_4 : linCheck 4 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (4, 5)`. -/
theorem check_lin_4_5 : linCheck 4 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (5, 0)`. -/
theorem check_lin_5_0 : linCheck 5 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (5, 1)`. -/
theorem check_lin_5_1 : linCheck 5 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (5, 2)`. -/
theorem check_lin_5_2 : linCheck 5 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (5, 3)`. -/
theorem check_lin_5_3 : linCheck 5 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (5, 4)`. -/
theorem check_lin_5_4 : linCheck 5 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (5, 5)`. -/
theorem check_lin_5_5 : linCheck 5 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (6, 0)`. -/
theorem check_lin_6_0 : linCheck 6 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (6, 1)`. -/
theorem check_lin_6_1 : linCheck 6 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (6, 2)`. -/
theorem check_lin_6_2 : linCheck 6 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (6, 3)`. -/
theorem check_lin_6_3 : linCheck 6 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (6, 4)`. -/
theorem check_lin_6_4 : linCheck 6 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (6, 5)`. -/
theorem check_lin_6_5 : linCheck 6 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (7, 0)`. -/
theorem check_lin_7_0 : linCheck 7 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (7, 1)`. -/
theorem check_lin_7_1 : linCheck 7 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (7, 2)`. -/
theorem check_lin_7_2 : linCheck 7 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (7, 3)`. -/
theorem check_lin_7_3 : linCheck 7 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (7, 4)`. -/
theorem check_lin_7_4 : linCheck 7 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (7, 5)`. -/
theorem check_lin_7_5 : linCheck 7 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (8, 0)`. -/
theorem check_lin_8_0 : linCheck 8 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (8, 1)`. -/
theorem check_lin_8_1 : linCheck 8 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (8, 2)`. -/
theorem check_lin_8_2 : linCheck 8 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (8, 3)`. -/
theorem check_lin_8_3 : linCheck 8 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (8, 4)`. -/
theorem check_lin_8_4 : linCheck 8 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (8, 5)`. -/
theorem check_lin_8_5 : linCheck 8 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (9, 0)`. -/
theorem check_lin_9_0 : linCheck 9 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (9, 1)`. -/
theorem check_lin_9_1 : linCheck 9 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (9, 2)`. -/
theorem check_lin_9_2 : linCheck 9 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (9, 3)`. -/
theorem check_lin_9_3 : linCheck 9 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (9, 4)`. -/
theorem check_lin_9_4 : linCheck 9 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (9, 5)`. -/
theorem check_lin_9_5 : linCheck 9 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (10, 0)`. -/
theorem check_lin_10_0 : linCheck 10 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (10, 1)`. -/
theorem check_lin_10_1 : linCheck 10 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (10, 2)`. -/
theorem check_lin_10_2 : linCheck 10 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (10, 3)`. -/
theorem check_lin_10_3 : linCheck 10 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (10, 4)`. -/
theorem check_lin_10_4 : linCheck 10 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (10, 5)`. -/
theorem check_lin_10_5 : linCheck 10 5 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (11, 0)`. -/
theorem check_lin_11_0 : linCheck 11 0 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (11, 1)`. -/
theorem check_lin_11_1 : linCheck 11 1 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (11, 2)`. -/
theorem check_lin_11_2 : linCheck 11 2 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (11, 3)`. -/
theorem check_lin_11_3 : linCheck 11 3 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (11, 4)`. -/
theorem check_lin_11_4 : linCheck 11 4 = true := by decide!
/-- (PROVED, kernel `decide!`) The check for `(k, g) = (11, 5)`. -/
theorem check_lin_11_5 : linCheck 11 5 = true := by decide!

/-- (PROVED) Check B for every `(k, g) ≠ (0, 0)`. -/
theorem lin_checks_all : ∀ (k : Fin 12) (g : Fin 6), (k, g) ≠ (0, 0) → linCheck k g = true
  | ⟨0, _⟩, ⟨0, _⟩, h => absurd rfl h
  | ⟨0, _⟩, ⟨1, _⟩, _ => check_lin_0_1
  | ⟨0, _⟩, ⟨2, _⟩, _ => check_lin_0_2
  | ⟨0, _⟩, ⟨3, _⟩, _ => check_lin_0_3
  | ⟨0, _⟩, ⟨4, _⟩, _ => check_lin_0_4
  | ⟨0, _⟩, ⟨5, _⟩, _ => check_lin_0_5
  | ⟨1, _⟩, ⟨0, _⟩, _ => check_lin_1_0
  | ⟨1, _⟩, ⟨1, _⟩, _ => check_lin_1_1
  | ⟨1, _⟩, ⟨2, _⟩, _ => check_lin_1_2
  | ⟨1, _⟩, ⟨3, _⟩, _ => check_lin_1_3
  | ⟨1, _⟩, ⟨4, _⟩, _ => check_lin_1_4
  | ⟨1, _⟩, ⟨5, _⟩, _ => check_lin_1_5
  | ⟨2, _⟩, ⟨0, _⟩, _ => check_lin_2_0
  | ⟨2, _⟩, ⟨1, _⟩, _ => check_lin_2_1
  | ⟨2, _⟩, ⟨2, _⟩, _ => check_lin_2_2
  | ⟨2, _⟩, ⟨3, _⟩, _ => check_lin_2_3
  | ⟨2, _⟩, ⟨4, _⟩, _ => check_lin_2_4
  | ⟨2, _⟩, ⟨5, _⟩, _ => check_lin_2_5
  | ⟨3, _⟩, ⟨0, _⟩, _ => check_lin_3_0
  | ⟨3, _⟩, ⟨1, _⟩, _ => check_lin_3_1
  | ⟨3, _⟩, ⟨2, _⟩, _ => check_lin_3_2
  | ⟨3, _⟩, ⟨3, _⟩, _ => check_lin_3_3
  | ⟨3, _⟩, ⟨4, _⟩, _ => check_lin_3_4
  | ⟨3, _⟩, ⟨5, _⟩, _ => check_lin_3_5
  | ⟨4, _⟩, ⟨0, _⟩, _ => check_lin_4_0
  | ⟨4, _⟩, ⟨1, _⟩, _ => check_lin_4_1
  | ⟨4, _⟩, ⟨2, _⟩, _ => check_lin_4_2
  | ⟨4, _⟩, ⟨3, _⟩, _ => check_lin_4_3
  | ⟨4, _⟩, ⟨4, _⟩, _ => check_lin_4_4
  | ⟨4, _⟩, ⟨5, _⟩, _ => check_lin_4_5
  | ⟨5, _⟩, ⟨0, _⟩, _ => check_lin_5_0
  | ⟨5, _⟩, ⟨1, _⟩, _ => check_lin_5_1
  | ⟨5, _⟩, ⟨2, _⟩, _ => check_lin_5_2
  | ⟨5, _⟩, ⟨3, _⟩, _ => check_lin_5_3
  | ⟨5, _⟩, ⟨4, _⟩, _ => check_lin_5_4
  | ⟨5, _⟩, ⟨5, _⟩, _ => check_lin_5_5
  | ⟨6, _⟩, ⟨0, _⟩, _ => check_lin_6_0
  | ⟨6, _⟩, ⟨1, _⟩, _ => check_lin_6_1
  | ⟨6, _⟩, ⟨2, _⟩, _ => check_lin_6_2
  | ⟨6, _⟩, ⟨3, _⟩, _ => check_lin_6_3
  | ⟨6, _⟩, ⟨4, _⟩, _ => check_lin_6_4
  | ⟨6, _⟩, ⟨5, _⟩, _ => check_lin_6_5
  | ⟨7, _⟩, ⟨0, _⟩, _ => check_lin_7_0
  | ⟨7, _⟩, ⟨1, _⟩, _ => check_lin_7_1
  | ⟨7, _⟩, ⟨2, _⟩, _ => check_lin_7_2
  | ⟨7, _⟩, ⟨3, _⟩, _ => check_lin_7_3
  | ⟨7, _⟩, ⟨4, _⟩, _ => check_lin_7_4
  | ⟨7, _⟩, ⟨5, _⟩, _ => check_lin_7_5
  | ⟨8, _⟩, ⟨0, _⟩, _ => check_lin_8_0
  | ⟨8, _⟩, ⟨1, _⟩, _ => check_lin_8_1
  | ⟨8, _⟩, ⟨2, _⟩, _ => check_lin_8_2
  | ⟨8, _⟩, ⟨3, _⟩, _ => check_lin_8_3
  | ⟨8, _⟩, ⟨4, _⟩, _ => check_lin_8_4
  | ⟨8, _⟩, ⟨5, _⟩, _ => check_lin_8_5
  | ⟨9, _⟩, ⟨0, _⟩, _ => check_lin_9_0
  | ⟨9, _⟩, ⟨1, _⟩, _ => check_lin_9_1
  | ⟨9, _⟩, ⟨2, _⟩, _ => check_lin_9_2
  | ⟨9, _⟩, ⟨3, _⟩, _ => check_lin_9_3
  | ⟨9, _⟩, ⟨4, _⟩, _ => check_lin_9_4
  | ⟨9, _⟩, ⟨5, _⟩, _ => check_lin_9_5
  | ⟨10, _⟩, ⟨0, _⟩, _ => check_lin_10_0
  | ⟨10, _⟩, ⟨1, _⟩, _ => check_lin_10_1
  | ⟨10, _⟩, ⟨2, _⟩, _ => check_lin_10_2
  | ⟨10, _⟩, ⟨3, _⟩, _ => check_lin_10_3
  | ⟨10, _⟩, ⟨4, _⟩, _ => check_lin_10_4
  | ⟨10, _⟩, ⟨5, _⟩, _ => check_lin_10_5
  | ⟨11, _⟩, ⟨0, _⟩, _ => check_lin_11_0
  | ⟨11, _⟩, ⟨1, _⟩, _ => check_lin_11_1
  | ⟨11, _⟩, ⟨2, _⟩, _ => check_lin_11_2
  | ⟨11, _⟩, ⟨3, _⟩, _ => check_lin_11_3
  | ⟨11, _⟩, ⟨4, _⟩, _ => check_lin_11_4
  | ⟨11, _⟩, ⟨5, _⟩, _ => check_lin_11_5
  | ⟨k + 12, h⟩, _, _ => absurd h (by omega)
  | _, ⟨g + 6, h⟩, _ => absurd h (by omega)

end DoubleDeal.Security.CovariantAffine
