/-
  GENERATED by proofs/doubledeal/analysis/v12-primenonswap/rank_family.py --lean;
  do not edit (CI: `rank_family.py --check`).

  HEAVY: the finite checks `RankChecks` of `DoubleDealSecurity/RankPartition.lean`, by
  kernel `decide!`: the structure of each family (`fam_struct_D`, no stem evaluation) and
  one stem evaluation per deck (`fam_c0_D_k_i`, 27). One theorem per deck because kernel
  memory is released between declarations but grows with the number of stem evaluations
  inside one `decide!`.
-/
import DoubleDealSecurity.RankPartition

namespace DoubleDeal.Security.RankPartition

/-- (PROVED, kernel `decide!`) The structure of family 0. -/
theorem fam_struct_0 : FamStruct 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 0, 0). -/
theorem fam_c0_0_0_0 : famC0Check 0 0 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 0, 1). -/
theorem fam_c0_0_0_1 : famC0Check 0 0 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 0, 2). -/
theorem fam_c0_0_0_2 : famC0Check 0 0 2 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 1, 0). -/
theorem fam_c0_0_1_0 : famC0Check 0 1 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 1, 1). -/
theorem fam_c0_0_1_1 : famC0Check 0 1 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 1, 2). -/
theorem fam_c0_0_1_2 : famC0Check 0 1 2 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 2, 0). -/
theorem fam_c0_0_2_0 : famC0Check 0 2 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 2, 1). -/
theorem fam_c0_0_2_1 : famC0Check 0 2 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 2, 2). -/
theorem fam_c0_0_2_2 : famC0Check 0 2 2 := by decide!
/-- (PROVED, kernel `decide!`) The structure of family 1. -/
theorem fam_struct_1 : FamStruct 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 0, 0). -/
theorem fam_c0_1_0_0 : famC0Check 1 0 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 0, 1). -/
theorem fam_c0_1_0_1 : famC0Check 1 0 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 0, 2). -/
theorem fam_c0_1_0_2 : famC0Check 1 0 2 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 1, 0). -/
theorem fam_c0_1_1_0 : famC0Check 1 1 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 1, 1). -/
theorem fam_c0_1_1_1 : famC0Check 1 1 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 1, 2). -/
theorem fam_c0_1_1_2 : famC0Check 1 1 2 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 2, 0). -/
theorem fam_c0_1_2_0 : famC0Check 1 2 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 2, 1). -/
theorem fam_c0_1_2_1 : famC0Check 1 2 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 2, 2). -/
theorem fam_c0_1_2_2 : famC0Check 1 2 2 := by decide!
/-- (PROVED, kernel `decide!`) The structure of family 2. -/
theorem fam_struct_2 : FamStruct 2 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 0, 0). -/
theorem fam_c0_2_0_0 : famC0Check 2 0 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 0, 1). -/
theorem fam_c0_2_0_1 : famC0Check 2 0 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 0, 2). -/
theorem fam_c0_2_0_2 : famC0Check 2 0 2 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 1, 0). -/
theorem fam_c0_2_1_0 : famC0Check 2 1 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 1, 1). -/
theorem fam_c0_2_1_1 : famC0Check 2 1 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 1, 2). -/
theorem fam_c0_2_1_2 : famC0Check 2 1 2 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 2, 0). -/
theorem fam_c0_2_2_0 : famC0Check 2 2 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 2, 1). -/
theorem fam_c0_2_2_1 : famC0Check 2 2 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 2, 2). -/
theorem fam_c0_2_2_2 : famC0Check 2 2 2 := by decide!

/-- (PROVED) Every stem-cell-0 check. -/
theorem fam_c0_all : ∀ D k i : Fin 3, famC0Check D k i
  | ⟨0, _⟩, ⟨0, _⟩, ⟨0, _⟩ => fam_c0_0_0_0
  | ⟨0, _⟩, ⟨0, _⟩, ⟨1, _⟩ => fam_c0_0_0_1
  | ⟨0, _⟩, ⟨0, _⟩, ⟨2, _⟩ => fam_c0_0_0_2
  | ⟨0, _⟩, ⟨1, _⟩, ⟨0, _⟩ => fam_c0_0_1_0
  | ⟨0, _⟩, ⟨1, _⟩, ⟨1, _⟩ => fam_c0_0_1_1
  | ⟨0, _⟩, ⟨1, _⟩, ⟨2, _⟩ => fam_c0_0_1_2
  | ⟨0, _⟩, ⟨2, _⟩, ⟨0, _⟩ => fam_c0_0_2_0
  | ⟨0, _⟩, ⟨2, _⟩, ⟨1, _⟩ => fam_c0_0_2_1
  | ⟨0, _⟩, ⟨2, _⟩, ⟨2, _⟩ => fam_c0_0_2_2
  | ⟨1, _⟩, ⟨0, _⟩, ⟨0, _⟩ => fam_c0_1_0_0
  | ⟨1, _⟩, ⟨0, _⟩, ⟨1, _⟩ => fam_c0_1_0_1
  | ⟨1, _⟩, ⟨0, _⟩, ⟨2, _⟩ => fam_c0_1_0_2
  | ⟨1, _⟩, ⟨1, _⟩, ⟨0, _⟩ => fam_c0_1_1_0
  | ⟨1, _⟩, ⟨1, _⟩, ⟨1, _⟩ => fam_c0_1_1_1
  | ⟨1, _⟩, ⟨1, _⟩, ⟨2, _⟩ => fam_c0_1_1_2
  | ⟨1, _⟩, ⟨2, _⟩, ⟨0, _⟩ => fam_c0_1_2_0
  | ⟨1, _⟩, ⟨2, _⟩, ⟨1, _⟩ => fam_c0_1_2_1
  | ⟨1, _⟩, ⟨2, _⟩, ⟨2, _⟩ => fam_c0_1_2_2
  | ⟨2, _⟩, ⟨0, _⟩, ⟨0, _⟩ => fam_c0_2_0_0
  | ⟨2, _⟩, ⟨0, _⟩, ⟨1, _⟩ => fam_c0_2_0_1
  | ⟨2, _⟩, ⟨0, _⟩, ⟨2, _⟩ => fam_c0_2_0_2
  | ⟨2, _⟩, ⟨1, _⟩, ⟨0, _⟩ => fam_c0_2_1_0
  | ⟨2, _⟩, ⟨1, _⟩, ⟨1, _⟩ => fam_c0_2_1_1
  | ⟨2, _⟩, ⟨1, _⟩, ⟨2, _⟩ => fam_c0_2_1_2
  | ⟨2, _⟩, ⟨2, _⟩, ⟨0, _⟩ => fam_c0_2_2_0
  | ⟨2, _⟩, ⟨2, _⟩, ⟨1, _⟩ => fam_c0_2_2_1
  | ⟨2, _⟩, ⟨2, _⟩, ⟨2, _⟩ => fam_c0_2_2_2

/-- (PROVED) The finite checks. -/
theorem rankChecks_ok : RankChecks := by
  refine ⟨fun D => ?_, fam_c0_all⟩
  match D with
  | ⟨0, _⟩ => exact fam_struct_0
  | ⟨1, _⟩ => exact fam_struct_1
  | ⟨2, _⟩ => exact fam_struct_2

end DoubleDeal.Security.RankPartition
