/-
  GENERATED by proofs/doubledeal/analysis/v12-primenonswap/v10sym_witness.py --lean;
  do not edit (CI: `v10sym_witness.py --check`).

  HEAVY: the finite checks of steps 2-4 by kernel `decide!`: `AffRankChecks`
  (`RankAffine`), `TauChecks` (`TauEq`) and `LabelChecks` (`LabelStep`). One stem
  evaluation per theorem (kernel memory grows with the number of stem evaluations inside
  one `decide!`).
-/
import DoubleDealSecurity.LabelStep

namespace DoubleDeal.Security.RankAffine

/-- (PROVED, kernel `decide!`) The structure of the affine family. -/
theorem aff_struct : AffStruct := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 0). -/
theorem aff_c0_0_0 : affC0Check 0 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 1). -/
theorem aff_c0_0_1 : affC0Check 0 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (0, 2). -/
theorem aff_c0_0_2 : affC0Check 0 2 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 0). -/
theorem aff_c0_1_0 : affC0Check 1 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 1). -/
theorem aff_c0_1_1 : affC0Check 1 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (1, 2). -/
theorem aff_c0_1_2 : affC0Check 1 2 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 0). -/
theorem aff_c0_2_0 : affC0Check 2 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 1). -/
theorem aff_c0_2_1 : affC0Check 2 1 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck (2, 2). -/
theorem aff_c0_2_2 : affC0Check 2 2 := by decide!

/-- (PROVED) Every stem-cell-0 check of the affine family. -/
theorem aff_c0_all : ∀ k i : Fin 3, affC0Check k i
  | ⟨0, _⟩, ⟨0, _⟩ => aff_c0_0_0
  | ⟨0, _⟩, ⟨1, _⟩ => aff_c0_0_1
  | ⟨0, _⟩, ⟨2, _⟩ => aff_c0_0_2
  | ⟨1, _⟩, ⟨0, _⟩ => aff_c0_1_0
  | ⟨1, _⟩, ⟨1, _⟩ => aff_c0_1_1
  | ⟨1, _⟩, ⟨2, _⟩ => aff_c0_1_2
  | ⟨2, _⟩, ⟨0, _⟩ => aff_c0_2_0
  | ⟨2, _⟩, ⟨1, _⟩ => aff_c0_2_1
  | ⟨2, _⟩, ⟨2, _⟩ => aff_c0_2_2

/-- (PROVED) The finite checks of step 2. -/
theorem affRankChecks_ok : AffRankChecks := ⟨aff_struct, aff_c0_all⟩

end DoubleDeal.Security.RankAffine

namespace DoubleDeal.Security.TauEq

/-- (PROVED, kernel `decide!`) Stem cell 0 of deck 0 is card 0. -/
theorem tau_g0_0 : tauG0 0 := by decide!
/-- (PROVED, kernel `decide!`) Stem cell 0 of deck 1 is card 0. -/
theorem tau_g0_1 : tauG0 1 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 1. -/
theorem tau_cand_1 : tauCand 1 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 2. -/
theorem tau_cand_2 : tauCand 2 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 3. -/
theorem tau_cand_3 : tauCand 3 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 4. -/
theorem tau_cand_4 : tauCand 4 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 5. -/
theorem tau_cand_5 : tauCand 5 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 6. -/
theorem tau_cand_6 : tauCand 6 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 7. -/
theorem tau_cand_7 : tauCand 7 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 8. -/
theorem tau_cand_8 : tauCand 8 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 9. -/
theorem tau_cand_9 : tauCand 9 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 10. -/
theorem tau_cand_10 : tauCand 10 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 11. -/
theorem tau_cand_11 : tauCand 11 := by decide!
/-- (PROVED, kernel `decide!`) The candidate sets for l = 12. -/
theorem tau_cand_12 : tauCand 12 := by decide!

/-- (PROVED) Every candidate-set check. -/
theorem tau_cand_all : ∀ l : ZMod 13, l ≠ 0 → tauCand l
  | ⟨0, _⟩, h => absurd rfl h
  | ⟨1, _⟩, _ => tau_cand_1
  | ⟨2, _⟩, _ => tau_cand_2
  | ⟨3, _⟩, _ => tau_cand_3
  | ⟨4, _⟩, _ => tau_cand_4
  | ⟨5, _⟩, _ => tau_cand_5
  | ⟨6, _⟩, _ => tau_cand_6
  | ⟨7, _⟩, _ => tau_cand_7
  | ⟨8, _⟩, _ => tau_cand_8
  | ⟨9, _⟩, _ => tau_cand_9
  | ⟨10, _⟩, _ => tau_cand_10
  | ⟨11, _⟩, _ => tau_cand_11
  | ⟨12, _⟩, _ => tau_cand_12

/-- (PROVED) The finite checks of step 3. -/
theorem tauChecks_ok : TauChecks :=
  ⟨fun i => match i with
    | ⟨0, _⟩ => tau_g0_0
    | ⟨1, _⟩ => tau_g0_1, tau_cand_all⟩

end DoubleDeal.Security.TauEq

namespace DoubleDeal.Security.LabelStep

/-- (PROVED, kernel `decide!`) The post-row structure of the deck. -/
theorem lab_struct : LabStruct := by decide!
/-- (PROVED, kernel `decide!`) `tr (eVec 1)` moves the source row of stem cell 0. -/
theorem lab_kill_1 : LabKill 1 := by decide!
/-- (PROVED, kernel `decide!`) `tr (eVec 2)` moves the source row of stem cell 0. -/
theorem lab_kill_2 : LabKill 2 := by decide!
/-- (PROVED, kernel `decide!`) `tr (eVec 3)` moves the source row of stem cell 0. -/
theorem lab_kill_3 : LabKill 3 := by decide!

/-- (PROVED) Every kill check. -/
theorem lab_kill_all : ∀ e : Fin 4, e ≠ 0 → LabKill e
  | ⟨0, _⟩, h => absurd rfl h
  | ⟨1, _⟩, _ => lab_kill_1
  | ⟨2, _⟩, _ => lab_kill_2
  | ⟨3, _⟩, _ => lab_kill_3

/-- (PROVED) The finite checks of step 4. -/
theorem labelChecks_ok : LabelChecks := ⟨lab_struct, lab_kill_all⟩

end DoubleDeal.Security.LabelStep
