"""Witness tables (and their Lean boilerplate) for the theorem that no card
transposition is COVARIANT for the unkeyed v12 round body F = GridCycle o stem,
for any output relabelling tau: `CovariantNarrow.roundBody_not_covariant_swap`
(heavy library), i.e. the conjecture roundBody_covariant_iff_id for transpositions.

EXHAUSTIVE over the 51 representatives (0 e), e = 1..51. Conjugation by v10Sym
reduces all 1326 transpositions to them (v10Sym acts simply transitively on the 52
cards). 51 is not minimal: the 1326 transpositions fall into 27 v10Sym-conjugation
orbits (printed below). Not a proof by itself: the heavy Lean library re-checks
every table entry by kernel decide!, so a wrong table fails the heavy build.

Argument. GridCycle puts walk card 0 at output seat 26, so F(m)[26] = stem(m)[0].
If F(s.m) = tau.F(m) on every deck, then g(s.m) = tau(g(m)) with g(m) = stem(m)[0].
Two decks m1 = identity deck and m2 = identity with seats i, j exchanged, with
g(m1) = g(m2) but g(s.m1) != g(s.m2), rule out every tau at once.

Usage:
    python3 cell0_witness.py           # print the table and the orbit count
    python3 cell0_witness.py --lean    # write the Lean files and the log
    python3 cell0_witness.py --check   # CI: fail if a Lean file or the log is stale

The search itself is shared with ../v12-primenonswap/aff_witness.py (cell0lib.py).
`cell0Pairs` is the union of the pairs used by both tables (one check A for both).

--lean writes
  security/DoubleDealSecurity/CovariantNarrowLists.lean (cell0Pairs, covW),
  security/DoubleDealSecurityHeavy/CovariantNarrowChecks.lean (pair_ok_*, cell0PairsCheck_ok,
    check_e1..51, checks_all),
  cell0_witness.log (the printed output).
"""
import contextlib
import io
import itertools
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
SEC = HERE.parents[1] / 'security'
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(REPO / 'tools'))
import cell0lib as C  # noqa: E402
from cell0lib import P  # noqa: E402
from gencheck import parser, emit  # noqa: E402

LISTS_OUT = SEC / 'DoubleDealSecurity' / 'CovariantNarrowLists.lean'
CHECKS_OUT = SEC / 'DoubleDealSecurityHeavy' / 'CovariantNarrowChecks.lean'
LOG_OUT = HERE / 'cell0_witness.log'
FIX = 'python3 proofs/doubledeal/analysis/v12-covariant/cell0_witness.py --lean'


def table():
    """(c, number of candidate pairs, covW with entry 0 unused, pairs used by covW,
    cell0Pairs)."""
    c, ncand, cov, _, pairs = C.tables()
    return c, ncand, [pairs[0]] + cov, sorted(set(cov)), pairs


def orbits():
    G = [P.v10sym(a, x) for a in range(13) for x in range(4)]
    assert len({tuple(s) for s in G}) == 52
    assert all(len({s[c] for s in G}) == 52 for c in range(52)), 'not simply transitive'
    seen, sizes = set(), []
    for a, b in itertools.combinations(range(52), 2):
        if (a, b) in seen:
            continue
        orb = {tuple(sorted((s[a], s[b]))) for s in G}
        seen |= orb
        sizes.append(len(orb))
    return sizes


def report(t):
    """Print the result of `table()` (computed once by the caller) and the orbit count."""
    c, ncand, tab, used, pairs = t
    print(f'g(identity deck) = {c}; single position swaps (i, j) keeping g: {ncand} of 1326')
    print(f'witness found for all 51 representatives (0 e); position pairs used: {used}')
    print(f'cell0Pairs (union with the pairs of aff_witness.py): {pairs}')
    print('covW =', tab)
    sizes = orbits()
    by = {k: sizes.count(k) for k in sorted(set(sizes))}
    print(f'v10Sym-conjugation orbits of the 1326 transpositions: {len(sizes)} '
          f'(sizes: {by}); the 51 representatives are not minimal')


def lists_text(tab, pairs):
    return f'''/-
  GENERATED by proofs/doubledeal/analysis/v12-covariant/cell0_witness.py --lean;
  do not edit (CI: `cell0_witness.py --check`).

  Witness seat pairs for `CovariantNarrow.cov0Check`: for representative `e`
  (1 ≤ e ≤ 51), `covW[e] = (i, j)` names the deck `posSwapDeck i j` (the identity
  deck with seats `i`, `j` exchanged). `cell0Pairs` lists the {len(pairs)} pairs used by
  `covW` or by `CovariantAffine.affW` (`aff_witness.py`), so one check A covers both.
  Entry 0 of `covW` is unused (set to the first pair). These lists are data, not
  trusted: the heavy library checks every entry by kernel `decide!`
  (`cell0PairsCheck_ok`, `check_e1` … `check_e51`), so a wrong entry fails the heavy
  build.
-/
namespace DoubleDeal.Security.CovariantNarrow

/-- The seat pairs used by `covW` and `affW` (each keeps stem cell 0 of the identity
    deck: check A, `pairsCheck cell0Pairs`). -/
def cell0Pairs : List (Fin 52 × Fin 52) :=
  {C.fmt(pairs)}

/-- The witness seat pair for each representative `e` (entry 0 unused). -/
def covW : List (Fin 52 × Fin 52) :=
  {C.fmt(tab)}

end DoubleDeal.Security.CovariantNarrow
'''


def checks_text(pairs):
    pthms = ''.join(f'/-- (PROVED, kernel `decide!`) Check A for the pair `({i}, {j})`. -/\n'
                    f'theorem pair_ok_{i}_{j} : g0 (posSwapDeck {i} {j}) = g0 idDeck := by decide!\n'
                    for i, j in pairs)
    pnames = ', '.join(f'pair_ok_{i}_{j}' for i, j in pairs)
    thms = ''.join(f'/-- (PROVED, kernel `decide!`) The check for `e = {k}`. -/\n'
                   f'theorem check_e{k} : cov0Check ⟨{k}, by decide⟩ = true := by decide!\n'
                   for k in range(1, 52))
    cases = ''.join(f'  | ⟨{k}, _⟩, _ => check_e{k}\n' for k in range(1, 52))
    return f'''/-
  GENERATED by proofs/doubledeal/analysis/v12-covariant/cell0_witness.py --lean;
  do not edit (CI: `cell0_witness.py --check`).

  HEAVY: check A (`pairsCheck cell0Pairs`, shared by `Cov0Checks` and
  `CovariantAffine.AffChecks`) as one kernel `decide!` per pair, and one kernel
  `decide!` per representative `e` of check B of `Cov0Checks`
  (`DoubleDealSecurity/CovariantNarrow.lean`); two stem evaluations each. One theorem
  per pair or `e` because kernel memory is released between declarations but grows
  with the number of stem evaluations inside one `decide!`.
-/
import DoubleDealSecurity.CovariantNarrow

namespace DoubleDeal.Security.CovariantNarrow

{pthms}
/-- (PROVED) Check A: every pair of `cell0Pairs` keeps stem cell 0 of the identity
    deck. -/
theorem cell0PairsCheck_ok : pairsCheck cell0Pairs = true := by
  simp only [pairsCheck, cell0Pairs, List.all_cons, List.all_nil, {pnames},
    beq_self_eq_true, Bool.and_self]

{thms}
/-- (PROVED) Check B for every `e ≠ 0`. -/
theorem checks_all : ∀ e : Fin 52, e ≠ 0 → cov0Check e = true
  | ⟨0, _⟩, h => absurd rfl h
{cases}  | ⟨n + 52, h⟩, _ => absurd h (by omega)

end DoubleDeal.Security.CovariantNarrow
'''


def main():
    args = cli.parse_args()
    t = table()
    if not (args.lean or args.check):
        report(t)
        return 0
    _, _, tab, _, pairs = t
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        report(t)
    rc = 0
    for path, text in ((LISTS_OUT, lists_text(tab, pairs)), (CHECKS_OUT, checks_text(pairs)),
                       (LOG_OUT, buf.getvalue())):
        rc |= emit(path, text, args.check, fix=FIX)
    return rc


cli = parser(__doc__)
cli.add_argument('--lean', action='store_true',
                 help='write the Lean files and the log (see the module docstring)')

if __name__ == '__main__':
    sys.exit(main())
