/-
  GENERATED by proofs/doubledeal/analysis/v12-covariant/cell0_witness.py --lean;
  do not edit (CI: `cell0_witness.py --check`).

  Witness seat pairs for `CovariantNarrow.cov0Check`: for representative `e`
  (1 ≤ e ≤ 51), `covW[e] = (i, j)` names the deck `posSwapDeck i j` (the identity
  deck with seats `i`, `j` exchanged). `goodPairs` lists the 4 pairs used.
  Entry 0 of `covW` is unused. These lists are data, not trusted: the heavy library
  checks every entry by kernel `decide!` (`goodPairsCheck_ok`, `check_e1` …
  `check_e51`), so a wrong entry fails the heavy build.
-/
namespace DoubleDeal.Security.CovariantNarrow

/-- The seat pairs used by `covW` (each keeps stem cell 0 of the identity deck). -/
def goodPairs : List (Fin 52 × Fin 52) :=
  [(1, 2), (1, 3), (1, 5), (1, 34)]

/-- The witness seat pair for each representative `e` (entry 0 unused). -/
def covW : List (Fin 52 × Fin 52) :=
  [(1, 2), (1, 5), (1, 5), (1, 34), (1, 2), (1, 2), (1, 3), (1, 2),
    (1, 2), (1, 2), (1, 3), (1, 5), (1, 2), (1, 2), (1, 2), (1, 3),
    (1, 2), (1, 2), (1, 3), (1, 3), (1, 2), (1, 2), (1, 2), (1, 3),
    (1, 3), (1, 2), (1, 2), (1, 3), (1, 2), (1, 2), (1, 2), (1, 2),
    (1, 2), (1, 5), (1, 2), (1, 2), (1, 2), (1, 2), (1, 2), (1, 3),
    (1, 2), (1, 2), (1, 3), (1, 5), (1, 2), (1, 2), (1, 3), (1, 2),
    (1, 2), (1, 2), (1, 3), (1, 5)]

end DoubleDeal.Security.CovariantNarrow
