/-
  GENERATED by proofs/doubledeal/analysis/v12-covariant/cell0_witness.py --lean;
  do not edit (CI: `cell0_witness.py --check`).

  Witness seat pairs for `CovariantNarrow.cov0Check`: for representative `e`
  (1 ≤ e ≤ 51), `covW[e] = (i, j)` names the deck `posSwapDeck i j` (the identity
  deck with seats `i`, `j` exchanged). `cell0Pairs` lists the 6 pairs used by
  `covW` or by `CovariantAffine.affW` (`aff_witness.py`), so one check A covers both.
  Entry 0 of `covW` is unused (set to the first pair). These lists are data, not
  trusted: the heavy library checks every entry by kernel `decide!`
  (`cell0PairsCheck_ok`, `check_e1` … `check_e51`), so a wrong entry fails the heavy
  build.
-/
namespace DoubleDeal.Security.CovariantNarrow

/-- The seat pairs used by `covW` and `affW` (each keeps stem cell 0 of the identity
    deck: check A, `pairsCheck cell0Pairs`). -/
def cell0Pairs : List (Fin 52 × Fin 52) :=
  [(1, 2), (1, 3), (1, 5), (1, 8), (1, 12), (1, 34)]

/-- The witness seat pair for each representative `e` (entry 0 unused). -/
def covW : List (Fin 52 × Fin 52) :=
  [(1, 2), (1, 5), (1, 5), (1, 34), (1, 2), (1, 2), (1, 3), (1, 2),
    (1, 2), (1, 2), (1, 3), (1, 5), (1, 2), (1, 2), (1, 2), (1, 3),
    (1, 2), (1, 2), (1, 3), (1, 3), (1, 2), (1, 2), (1, 2), (1, 3),
    (1, 3), (1, 2), (1, 2), (1, 3), (1, 2), (1, 2), (1, 2), (1, 2),
    (1, 2), (1, 5), (1, 2), (1, 2), (1, 2), (1, 2), (1, 2), (1, 3),
    (1, 2), (1, 2), (1, 3), (1, 5), (1, 2), (1, 2), (1, 3), (1, 2),
    (1, 2), (1, 2), (1, 3), (1, 5)]

end DoubleDeal.Security.CovariantNarrow
