/-
  GENERATED by proofs/doubledeal/analysis/v12-primenonswap/aff_witness.py --lean;
  do not edit (CI: `aff_witness.py --check`).

  The tables of `CovariantAffine.linSym` (from `analysis/v12-covariant/cell0lib.py`,
  the same data the witness search uses), and the witness seat pairs for
  `CovariantAffine.linCheck`: for the linear part `(k, g)` (`(k, g) ≠ (0, 0)`),
  `affW[6 k + g] = (i, j)` names the deck `posSwapDeck i j` (the identity deck with
  seats `i`, `j` exchanged); every pair is in `CovariantNarrow.cell0Pairs`. Entry 0
  of `affW` is unused (set to the first pair of `cell0Pairs`). These lists are data,
  not trusted: Lean proves the tables give inverse bijections and linear maps
  (`linFn_left`, `linFn_right`, `glApp_gfAdd`), and the heavy library checks every
  witness by kernel `decide!` (`cell0PairsCheck_ok`, `check_lin_*`).
-/
namespace DoubleDeal.Security.CovariantAffine

/-- GL(2,2) on GF(4) labels `0..3` (bit 0 = `l % 2`, bit 1 = `l / 2`): row `g` lists
    the images of labels 0, 1, 2, 3. Row 0 is the identity. -/
def glTab : List (List Nat) :=
  [[0, 1, 2, 3], [0, 2, 1, 3], [0, 1, 3, 2], [0, 3, 2, 1], [0, 2, 3, 1], [0, 3, 1, 2]]

/-- `glInvTab[g]`: the index of the inverse matrix of row `g`. -/
def glInvTab : List (Fin 6) :=
  [0, 1, 2, 3, 5, 4]

/-- `unitInvTab[k] = k'` with `(k + 1)(k' + 1) ≡ 1 (mod 13)`. -/
def unitInvTab : List (Fin 12) :=
  [0, 6, 8, 9, 7, 10, 1, 4, 2, 3, 5, 11]

/-- The witness seat pair for each linear part, at index `6 k + g` (entry 0 unused). -/
def affW : List (Fin 52 × Fin 52) :=
  [(1, 2), (1, 5), (1, 5), (1, 5), (1, 5), (1, 5), (1, 8), (1, 8),
    (1, 5), (1, 5), (1, 8), (1, 5), (1, 5), (1, 5), (1, 5), (1, 5),
    (1, 5), (1, 5), (1, 5), (1, 8), (1, 5), (1, 12), (1, 5), (1, 8),
    (1, 8), (1, 5), (1, 12), (1, 5), (1, 5), (1, 8), (1, 5), (1, 5),
    (1, 5), (1, 5), (1, 5), (1, 5), (1, 8), (1, 12), (1, 12), (1, 5),
    (1, 8), (1, 5), (1, 5), (1, 5), (1, 5), (1, 8), (1, 5), (1, 5),
    (1, 8), (1, 8), (1, 5), (1, 8), (1, 5), (1, 5), (1, 5), (1, 8),
    (1, 5), (1, 5), (1, 8), (1, 5), (1, 5), (1, 5), (1, 5), (1, 5),
    (1, 5), (1, 5), (1, 5), (1, 5), (1, 5), (1, 5), (1, 8), (1, 8)]

end DoubleDeal.Security.CovariantAffine
