/-
  GENERATED by proofs/doubledeal/analysis/v12-primenonswap/aff_witness.py --lean;
  do not edit (CI: `aff_witness.py --check`).

  Witness seat pairs for `CovariantAffine.linCheck`: for the linear part `(k, g)`
  (`(k, g) ≠ (0, 0)`), `affW[6 k + g] = (i, j)` names the deck `posSwapDeck i j` (the
  identity deck with seats `i`, `j` exchanged). `affPairs` lists the 3 pairs used.
  Entry 0 of `affW` is unused. These lists are data, not trusted: the heavy library
  checks every entry by kernel `decide!` (`affPairsCheck_ok`, `check_lin_*`), so a
  wrong entry fails the heavy build.
-/
namespace DoubleDeal.Security.CovariantAffine

/-- The seat pairs used by `affW` (each keeps stem cell 0 of the identity deck). -/
def affPairs : List (Fin 52 × Fin 52) :=
  [(1, 5), (1, 8), (1, 12)]

/-- The witness seat pair for each linear part, at index `6 k + g` (entry 0 unused). -/
def affW : List (Fin 52 × Fin 52) :=
  [(1, 2), (1, 5), (1, 5), (1, 5), (1, 5), (1, 5), (1, 8), (1, 8),
    (1, 5), (1, 5), (1, 8), (1, 5), (1, 5), (1, 5), (1, 5), (1, 5),
    (1, 5), (1, 5), (1, 5), (1, 8), (1, 5), (1, 12), (1, 5), (1, 8),
    (1, 8), (1, 5), (1, 12), (1, 5), (1, 5), (1, 8), (1, 5), (1, 5),
    (1, 5), (1, 5), (1, 5), (1, 5), (1, 8), (1, 12), (1, 12), (1, 5),
    (1, 8), (1, 5), (1, 5), (1, 5), (1, 5), (1, 8), (1, 5), (1, 5),
    (1, 8), (1, 8), (1, 5), (1, 8), (1, 5), (1, 5), (1, 5), (1, 8),
    (1, 5), (1, 5), (1, 8), (1, 5), (1, 5), (1, 5), (1, 5), (1, 5),
    (1, 5), (1, 5), (1, 5), (1, 5), (1, 5), (1, 5), (1, 8), (1, 8)]

end DoubleDeal.Security.CovariantAffine
