/-
  GENERATED by proofs/doubledeal/analysis/v12-diffusion/prefix_survival.py --lean;
  do not edit (CI: `prefix_survival.py --check`).

  For `v10Sym 0 3` (♣↔♠, ♥↔♦, same rank) and first card
  K♣ (`LKC`) or K♠ (`LKS`): the pairs `(c1, c2)` of second and third cards, with
  `c0, c1, c2` distinct, for which the seats of walk cards 1, 2, 3 are unchanged.
  15 + 15 = 30 pairs; with the first card these are the
  30 first-card triples `T03` of `GridCycleSurvival.lean`
  (30 / (52 · 51 · 50) = 1/4420 = the exact `A_4` in
  `analysis/v12-diffusion/prefix_survival.log`). Only K♣ / K♠ can start a surviving
  deck (`gcSurvives_first`).

  These lists are data, not trusted: the kernel checks that they are complete
  (`Check3 KC LKC`, `Check3 KS LKS`, `decide!` in
  `DoubleDealSecurityHeavy/GridCycleSurvival.lean`), so a wrong list fails the heavy
  build. Card ids are `13 · suit + rank` (suits ♣ ♥ ♠ ♦, ranks A..K).
-/
namespace DoubleDeal.Security.GridCycleSurvival

/-- Second and third cards keeping seats 1..3 unchanged under `v10Sym 0 3`, first card K♣ (card 12). -/
def LKC : List (Fin 52 × Fin 52) :=
  [(0, 38), (1, 38), (2, 38), (3, 38), (4, 38), (5, 38), (6, 38), (7, 38),
    (8, 38), (9, 38), (10, 38), (11, 38), (13, 24), (50, 13), (51, 25)]

/-- Second and third cards keeping seats 1..3 unchanged under `v10Sym 0 3`, first card K♠ (card 38). -/
def LKS : List (Fin 52 × Fin 52) :=
  [(24, 39), (25, 51), (26, 12), (27, 12), (28, 12), (29, 12), (30, 12), (31, 12),
    (32, 12), (33, 12), (34, 12), (35, 12), (36, 12), (37, 12), (39, 50)]

end DoubleDeal.Security.GridCycleSurvival
